### ISSUE TITLE
What happened to the old project?

### ISSUE THREAD

**Issue by ghost** [Azimer/AziAudio#1]
If I'm not mistaken here, everything is wiped clean?

I can only find a initial commit and nothing else, but if everything is in order then by all means close this issue?!?

**Comment by Azimer** [comment]
Sorry @SigmaVirus .  I wanted to purge the repository and remove sections.  I will continue to provide updates here to the GPL licensed code but will no longer provide source updates to my new audio code.  It's unnecessary drama but what I felt I had to do to keep working on a project I do 100% for free.  I've only ever asked for a little respect in return.

That said...  I have tagged a WIP 10 release and included a new binary.  https://github.com/Azimer/AziAudio/releases/tag/WIP10.  Again, sorry if this causes confusion.  Bottom line, I didn't stop working on it and I won't stop updating source or binaries here.

**Comment by ghost** [comment]
Thanks @Azimer 
So glad to hear everything is all good, keep up the good work!
