### ISSUE TITLE
Investigate crash switching between plugins (XAudio2)

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#1]
There is a bug that causes a crash to spontaneously happen switching between audio plugins using XAudio2.  This crash appears to be tied to the use of wxWidgets in other plugins and CoInitialize needed for XAudio2.  For some reason the internal XAudio2 thread is unloaded from memory prior to the DLL closing.

**Comment by Frank-74** [comment]
I just changed 	CoInitializeEx to APARTMENTTHREADED, instead of MULTITHREADED, I also removed all instances of CoUninitialize() except in XAudio2SoundDriver::~XAudio2SoundDriver().

Been trying to get it to crash switching between the DS8 and XA2 versions and its not crashed yet after 10 or so attempts with Goldeneye, TWINE, Perfect Dark.  What's the foolproof way of making it crash so I can thoroughly test it?

**Comment by Azimer** [comment]
Usually going into the plugin selection dialog.  Play a game... end emulation... switch plugins.  Switch back.  Play a game.  Eventually it will crash.

**Comment by Frank-74** [comment]
I spoke too soon, just crashed with Turok2 changing from DS8 to XA2.

**Comment by Azimer** [comment]
I think if you removed every plugin except for Jabo's (since his UI elements don't use wxWidgets), the crash will not be there.  It seems isolated to wxWidgets using CoInitialize and possibly conflicting with AziAudio.dll.  I think the trashing of plugin opening and closing is causing issues.

**Comment by Frank-74** [comment]
I started having a more serious crash.  Closing PJ64 while a game is running with XAudio2, made my PC lockup.  Had to pull the plug.

I've just been experimenting in this branch, and it no longer locks my PC when shutting down PJ64 with a game running.
https://github.com/Frank-74/AziAudio/tree/Fix-XAudio2-Crash

I've only tested it briefly with a couple of games where it crashed every time before.

**Comment by Azimer** [comment]
I can see removing the extra CoInitializes but to remove the others are a pretty serious change that need extensive testing.  Did the crash happen one time or were you able to consistently reproduce it?  What specs and scenario were you able to reproduce this issue with?

**Comment by Frank-74** [comment]
I selected Azimer's XA2 as the default plugin in PJ64.  Settings were FAT=0, Sync using audio off.  Open PJ64, run Goldeneye, close PJ64 window.  Mouse cursor disappears, system locks up.  Happened everytime.

**Comment by Azimer** [comment]
Are you windows xp, 7 or 8 ?

**Comment by Frank-74** [comment]
XP SP3.

**Comment by Frank-74** [comment]
I though maybe this was causing a problem.
```cpp
EXPORT void CALL CloseDLL(void) {
	ChangeABI (0);
	if (audioIsInitialized == TRUE) snd.DeInitialize();
	snd.DeInitialize();
}
```
If the condition is true, it does DeInitialize twice?
And ```cpp if (hMutex != NULL) ``` condition I removed because hMutex NULL was already tested at the top

**Comment by LegendOfDragoon** [comment]
I've been tracking down various bugs lately. Is there a way to consistently reproduce this issue?

**Comment by Azimer** [comment]
The mutex condition testing happening twice was intention.  The first test is if the mutex exist, you need to capture the mutex.  Then the second is if the mutex exist, release that captured mutex and finally destroying the mutex.  You can get a crash by trying to destroy the mutex while it's captured by another thread.

The quoted code is invalid and should be fixed.  However, it isn't responsible for your crash.  The last statement in the TearDown routine is dllInitialized = false; and the first is if (dllInitialized == false) return;,  So calling it twice is simply a noop on the second call.

**Comment by Frank-74** [comment]
With the changes I made, it seems neither the DS8 or XA2 plugins are recognised by PJ64 with Windows 7 Professional 64-bit.  But they are with XP.  The CloseDLL()  call at the start of InitiateAudio in main.cpp is the cause of this.

**Comment by therandomizer85** [comment]
Well, it's in vain because no matter what I do, no matter how I install the plugins or tell the emulator where to find them, the result is always the same and it simply won't find any of the 0.70 WIP versions  :( I am very close to giving up ><

**Comment by Frank-74** [comment]
Here are my audio plugin options on XP.
![settings3](https://cloud.githubusercontent.com/assets/11056843/7576540/c9255678-f836-11e4-9ff6-e18841dd72a9.png)
And I gave the randomizer my build and here's his plugin options with same settings.
![randomizer1](https://cloud.githubusercontent.com/assets/11056843/7576545/e197d8c0-f836-11e4-9613-5b805a248395.png)

**Comment by therandomizer85** [comment]
Well, then I effed something up and/or and never to be able to help with testing. Figures :( I knew that I screwed up.

**Comment by therandomizer85** [comment]
You know what, screw it, I'm posting it on here, showing that I'm doing everything correctly, step by step. 

https://www.youtube.com/watch?v=xFJ-rDA7pzM

**Comment by Frank-74** [comment]
@therandomizer85
I don't think you've done anything wrong.  You've found through testing, that the plugin doesn't show up in W7 64bit.  It might be something wrong with the ming build.  It will take me a while to rebuild the current master with Visual Studio compiler.  I have to set up a new project in codeblocks and add libraries manually.  I never got it to work in VS2008 Professional, the VS2008 included is not recognised in Professional version.

**Comment by therandomizer85** [comment]
Damn, so that means that it's not going to be easy to resolve, if I understand what you're saying correctly, but since I'm not a programmer, and since I don't know the rudiments that well, I could be off. But it's weird, I do remember seeing a build of WIP 5 showing up on Win 7 before, not even the EmuCR builds from two days ago show up, ugh.... Do you need the video link?  I still feel bad because of me, like, I mean, what would happen if I never pointed it out/reported the issue?

**Comment by Frank-74** [comment]
@therandomizer85
You can try to install this.

Microsoft Visual C++ 2008 Redistributable Package (x64)
https://www.microsoft.com/en-gb/download/details.aspx?id=15336

You probably need to reboot after installing.  Does this work in Win 7?

**Comment by therandomizer85** [comment]
Why do I need to install this? Are you asking me to compile something?

**Comment by therandomizer85** [comment]
Nope. Didn't prompt me for a reboot, and it made no difference.

**Comment by Frank-74** [comment]
Come to think of it, if Pj64 is running with my build, you should already have the VS2008 redist.  The problem might be due to 64 bit.  I don't know.

**Comment by therandomizer85** [comment]
I f***ing give up. I just give up. I'm sorry for letting you down, man, I can't apologize enough :'(

**Comment by LegendOfDragoon** [comment]
Does Azimer's XA2 crash on PJ64 1.7?

**Comment by Frank-74** [comment]
@LegendOfDragoon Don't know, but commenting out these coinitialize seems to have helped.
'Project64\N64 System\N64 Class.cpp'
```cpp
void CN64System::StartEmulationThread (  ThreadInfo * Info ) 
{
	//CoInitialize(NULL);
	
	EmulationStarting(*Info->ThreadHandle,Info->ThreadID);
	delete Info->ThreadHandle;
	delete Info;

	//CoUninitialize();
}
```

**Comment by Frank-74** [comment]
Since doing the above change to Project64 (https://github.com/Azimer/AziAudio/issues/1#issuecomment-101430955), I've been having crashless sessions.  I've just played Goldeneye, Conker's, Armorines, Turok 2, Mario Tennis, Monaco Grand Prix 2, Nascar 2000.  Switched from XAudio2 to Jabo and DS8 a few times, used PJ Glide a couple of times, switched from 1.6.1 to 1.7 to Glide, DS8 to XA2, End Emulation, play another game etc....

To top it off I quit Project64 with a game running.  Still no crash.  I didn't change anything in the current AziAudio master.  Just built a new aziaudio-master zip with VS2008 and tested.

**Comment by therandomizer85** [comment]
Do we have a solution for the plugins not being detected? It's been a couple of days, just checking up :3

**Comment by LegendOfDragoon** [comment]
I wouldn't be surprised if the problem for @therandomizer85 was missing runtime libs.

I don't experience any plugin related issues for crashing, except for the save state issue.

**Comment by Frank-74** [comment]
therandomizer85's problem seems to be solved with the VS2008 build.  MinGW build doesn't show up for him, but VS2008 build does.

**Comment by cxd4** [comment]
You need `LIBGCC_S_DW2-1.DLL` and `LIBSTDC++-6.DLL` to use the MinGW g++ build, as I have the script set up to enforce dynamically linking those DLLs--statically linking them would be disastrous to the final size.

**Comment by therandomizer85** [comment]
I don't know why I was the only one to have the issue, I really don't, and it was infuriating since no one else could reproduce it. That being said, the newly compiled build actually gets detected and if there are any skeptics, I'd be more than happy to show the video I recorded.

**Comment by cxd4** [comment]
>I wouldn't be surprised if the problem for @therandomizer85 was missing runtime libs.

Also Project64 1.6 did a better job of reporting missing run-times when a plugin fails to load.  With Project64 2.x it just silently says that the plugin failed to load without telling you why / what missing DLLs are missing.

**Comment by therandomizer85** [comment]
Ugh, I would've been better off had I never reported it -_- C'est la vie...

**Comment by cxd4** [comment]
You're not French.

**Comment by therandomizer85** [comment]
"Such is life", that's all I'm saying. I shouldn't have filed the report, and yet, I'm the only one who had the problem, therefore, it was big effing waste of everyone's time. Go fig. I'm not French, but it's a common phrase. So sorry for using French.

**Comment by Frank-74** [comment]
I've had another crash, so did a search on Project64 for all CoInitialize and CoUnitialize and there's a CoInitialize without a CoUnitialize in Recompiler Class.cpp at `void CRecompiler::Run()`.

**Comment by therandomizer85** [comment]
Audio sounds garbled on Pilotwings 64, even with FAT off.

**Comment by Frank-74** [comment]
@therandomizer85 Issue is here https://github.com/Azimer/AziAudio/issues/6.  Turn off Use HLE Audio in PJ64 plugin settings.  Also turn of Use TLB and Advanced block linking to stop it freezing.

**Comment by therandomizer85** [comment]
I think it was due to the GlideN64 plugin slowing down at the intro, but I'll try that other option, and yeah, I'm using the build sent to me last night.  HLE Audio is off by default.

**Comment by Frank-74** [comment]
> I've had another crash, so did a search on Project64 for all CoInitialize and CoUnitialize and there's a CoInitialize without a CoUnitialize in Recompiler Class.cpp at void CRecompiler::Run().

Strange thing is if I remove that CoInitialize in Recompiler, the current Azimer XA2 starts up with no sound.  However, going to Options > Settings and switching to Jabo's, resume (with sound), and then again switch back to Azimer XA2, now we have sound.  Weird...

**Comment by LegendOfDragoon** [comment]
I tested on PJ64 1.7. I switched plugins dozens of times and didn't crash once. As I suspected, there's no issue with switching plugins anymore.

@Azimer I think it's best to focus on fixing known issues, such as loading save states as well as that WDC problem you mentioned. In my experience, fixing known problems also fixed unknown problems that I later encountered in other plugins. Also, I think that AbortAiUpdate code is unnecessary. I've debugged it and it wasn't effective, in my experience.

**Comment by LegendOfDragoon** [comment]
I guess I spoke a little too soon. I now see the Xaudio_unloaded. However, simply switching games doesn't exactly trigger it, from what I've seen. There's more to it than that. I'll try looking into it, since I enjoy debugging :smile: .

**Comment by Frank-74** [comment]
@LegendOfDragoon Good luck with that, I tried for a week and couldn't find a solution.  Its wxWidgets CoInitialize conflict with PJ64.  Not sure if wxWidgets was used in 1.7?

**Comment by Frank-74** [comment]
Removing snd.DeInitialize(); from RomOpen and RomClosed, as well as audioIsInitialized = FALSE; in RomClosed only. And no more crashing here switching between DS8 and XA2.

**Comment by LegendOfDragoon** [comment]
I fixed the threading issue in PJ64 2.2 with AiUpdate, so now it should no longer crash in AiUpdate or get that Dll_unloaded error. Only thing left, is the XAudio_unloaded error. That issue might even be related to the fact that I have older versions of the XA2 plugin in my directory. I'll need to look into it.

If anyone knows a consistent way to reproduce the XAudio_unloaded error, let me know, so I can possibly track it down and fix :smile: .

**Comment by Frank-74** [comment]
Start with XA2, switch in game to DS8, switch back in game to XA2.  No sound.
Removing just snd.DeInitialize(); from RomOpen fixes it here.  With the fix to Project64 everything seems fine now.

**Comment by SwooshyCueb** [comment]
Using the current codebase, the XA2 plugin outright crashes when emulation starts for me. It's probably not related (since I'm using wine and/or this could've been caused by a more recent code change) but I thought it might be worth mentioning.

**Comment by Frank-74** [comment]
This should no longer be an issue with Project64.  Project64 removed wxwidgets so there shouldn't be a conflict anymore.  Also, I think removing the win32 hack for ancient pre 1.5.2 jabo plugins has helped.  The hack created another empty thread and called main twice.  The hack is enabled for audio, gfx, input plugins.  My PR to have it removed isn't merged yet.  Jabo's 1.5.2, 1.6, 1.6.1 and 1.7 plugins all still work fine without the hack anyway.

**Comment by LegendOfDragoon** [comment]
I consistently get a crash if I load a game, end emulation, then edit game settings. Haven't tried Frank's PR for PJ64 yet though.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
I just rebuilt the PJ64 solution with VS2015, with #1272.  And built both XA2 and DS8 with VS2015 as well.  I don't get any crash if I load a game, end emulation, then edit game settings.

My complete build here if you want to test: https://www.dropbox.com/s/aa06fxu66p3lsfy/Project64.zip?dl=1

**Comment by LegendOfDragoon** [comment]
@Frank-74 it still crashed on my end, but it seemed to get further. I think maybe since I have multiple versions of the XA2 plugin in the plugin directory, it works different on my end.

**Comment by Frank-74** [comment]
Just tested myself with Glide64 Final in plugins folder, I get wxWidgets Error: Cannot initialise OLE.  When opening edit game settings after using XA2.  But I click OK and the settings appear.

I get no crashes or errors with any other plugins in plugin folder.  Probably having multiple XA2 versions in plugin directory causes it.

**Comment by Frank-74** [comment]
Found this in: https://github.com/project64/project64/blob/master/Source/Project64-core/N64System/EmulationThread.cpp#L33-L37

CoInitialize(NULL);
EmulationStarting(thread);
CoUninitialize();

What would be the point of wrapping EmulationStarting(thread) with CoInitialise(NULL)/CoUnitialise()?

**Comment by Azimer** [comment]
I run minimalist here.  I don't have a bunch of plugins but if you can help determine the minimum plugins needed to cause this error, I can investigate.  It was definitely related to CoInitialize/CoUninitialize and Glide64.  A thought is to use late loading of the XAudio objects when the audio begins playing and detach them from the Initialize, CloseDLL, RomOpen, RomClose hooks.

**Comment by Frank-74** [comment]
With only the plugins that come with latest PJ64 2.3.2.  I get no crashes.

Add Glide64 Final to plugins folder.
When using default jabo 1.7 gfx and XA2 Audio, I get wxWidgets OLE error after end emulation/edit game settings.
When using Glide64 Final and XA2 Audio, I don't get wxWidgets OLE error after end emulation/edit game settings.  But I get fatal crash while running a game and switching gfx plugin from Glide64 Final to Jabo.  Crash only happens when using XA2 Audio.

**Comment by LegendOfDragoon** [comment]
I copied the XA2 build, to see if simply having a duplicate copy of the plugin in the folder would cause any problems and still no crash when editing game settings. So never-mind about the edit game setting crash. I don't need to keep old versions of the XA2 plugin :smile: .

To reproduce the DLL unloaded issue, you simply run a game, end emulation, edit game settings, then close PJ64.

**Comment by Azimer** [comment]
In the latest Project64, I noticed Initialize isn't being called when pulling up the settings dialog.  This is fantastic.  XAudio2 is not being initialized when this occurs, so if there are any crashes with the latest plugin, it's not related directly.  I still think it's related to Glide64 Final (old versions) and wxWidgets.  I can't recreate this with the latest debug version of Glide64 and the latest debug version of AziAudio XA2.

**Comment by Azimer** [comment]
I've not been able to reproduce this issue without using the older version of Glide64.  I will close this issue in 14 days if I don't get anything more on it.

**Comment by cxd4** [comment]
Project64 Glide64 was using wxWidgets.

It's not anymore.  I doubt you'll reproduce this issue on any up-to-date builds of Project64.
