### ISSUE TITLE
Latest WIP build found here (Tribute to Azimer)

### ISSUE THREAD

**Issue by ghost** [Azimer/AziAudio#10]
Built with Visual Studio 2019 Professional, the latest of the latest, I present to you **WIP 10** (both x86 and x64)

[AziAudio v0.70 WIP10.zip](https://github.com/Azimer/AziAudio/files/4792326/AziAudio.v0.70.WIP10.zip)

OK OK, technically there is already a WIP 10 build under [releases](https://github.com/Azimer/AziAudio/releases) but it's from Dec 28 2017 and although there is only 5 commits since then they are pretty substantial and important.

Here's hoping that v0.70 Final will surface 2020!

**Comment by ghost** [comment]
So yeah, the plugin is working great and all but I was just wondering if there is any possibility to disable the logging console that appears all the time when ever you want to configure the plugin or play a game?

I realize I'm just talking to myself here but if anyone with the knowledge know how to disable the logging console window then speak now or be silent forever.

PS.

WIP 9 does not have a logging console at all.

**Comment by ghost** [comment]
No one cares anymore, not even the owner.
R.I.P AziAudio!

**Comment by oddMLan** [comment]
No need to be rude. Azimer is busy with real life stuff. I'm sure he'll come back to this before the end of the year.

**Comment by ghost** [comment]
I'm not being rude, I'm just sad and depressed.

**Comment by CrashOveride95** [comment]
Sad and depressed over a random person on the internet not working on his audio plugin because of other things like IRL? Grow up.

**Comment by ghost** [comment]
Why do random people start to drop in when I closed the issue, the issue is closed, buried, dead and finito.

Nice way to end the post BTW, grow up? How old are you 12? I'm 35 and I'm not going to grow up just because you said so.

STOP RESPOND TO THIS ISSUE! KTHXBYE
