### ISSUE TITLE
Multi-backend plugin

### ISSUE THREAD

**Issue by SwooshyCueb** [Azimer/AziAudio#105]
I wanted to go ahead and work on merging the two versions of the plugin into a single plugin. There are two (or maybe more?) ways we could approach this and I wanted some input before I start.
1. On plugin initialization (maybe in DllMain or something), enumerate the devices with each backend and add them all into the device list with the name of the backend in parenthesis next to the device name. Which backend is used will depend completely on the device chosen from the device list.
2. Include another combo box in the configuration dialog for the backend. Update the device list whenever this is changed.

Personally, I'd like to give the first approach a shot.

**Comment by cxd4** [comment]
Yeah first sounds good, though I would think InitiateAudio would be the place for it instead of DllMain.

**Comment by Azimer** [comment]
All initialization should happen in InitiateAudio. as the spec defines.  It is my intention for the plugin to become a multi-backend plugin.  Furthermore, I wish for them to all share the same buffer/emulation code and differ only in how they consume that buffer.  For example, when a new buffer is added, the samples will be loaded into a common memory location.  AI flags will be set appropriately.  The specific audio driver will call an inherit method to read from the memory location and return back the number of samples needed.  The inherited method will remove the number of samples needed and do the appropriate AI emulation needed when a buffer is fully consumed.  This way we should have a common expectation for the way audio is emulated regardless of API.  Make sense?

**Comment by Azimer** [comment]
This will be getting some attention after I complete the audio code.

**Comment by Azimer** [comment]
Implemented in 0.70 WIP9.  Will iterate through to refine the changes.
