### ISSUE TITLE
Some possibly wrong algorithm in ENVMIXER?

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#11]
I was just appending this commit to my pull request to get rid of the in-line asm:
https://github.com/cxd4/AziAudio/commit/360197dba34e9ca9a3c5b85e4abcab38f949fd13

(I also unified the C code to a single function we can call and re-use instead of pasting the same code twice.)

So, in the process, all of my steps worked out to this.

1)  Starting with the original asm code @Azimer used:

``` asm
__asm {
    mov ecx, dword ptr [LAdderEnd];
    mov eax, dword ptr [LRamp];
    imul    ecx;
    shrd    eax, edx, 16;
    mov dword ptr [LAdderEnd], eax;
    mov eax, dword ptr [LAdderStart];
    mov dword ptr [LAcc], eax;
    mov dword ptr [LAdderStart], ecx;
    sub ecx, eax;
    sar ecx, 3;
    mov dword ptr [LVol], ecx;
}
```

2)  I rewrote it as C code after enough analysis of what the asm did:

``` c
    s64 product, product_shifted;

    product = (s64)LRamp * (s64)LAdderEnd;
    product_shifted = product >> 16;
    LAcc = LAdderStart;
    LAdderStart = LAdderEnd;
    LVol = (LAdderEnd - LAcc) / 8;
    LAdderEnd = (s32)(product_shifted & 0xFFFFFFFFul);
```

3)  I _later_ realized Azimer already had a C translation of the asm, in comments below:

``` c
//LAcc = LAdderStart;
//LVol = (LAdderEnd - LAdderStart) >> 3;
//LAdderEnd = ((s64)LAdderEnd * (s64)LRamp) >> 16;
//LAdderStart = ((s64)LAcc * (s64)LRamp) >> 16;
```

So basically, unless I mis-translated the inline asm code, then maybe the asm code used here to begin with may be responsible for an audio HLE bug somewhere?

The key difference I saw was in the inline asm code we had this:

``` asm
    mov ecx, dword ptr [LAdderEnd];
    mov eax, dword ptr [LRamp];
    imul    ecx;
... # no reads or writes from or to ecx up until this point:
    mov dword ptr [LAdderStart], ecx;
```

This seems to have been what caused the difference between my C and the one in the comments Azimer did.  In my interpretation, I read it as:

``` c
    LAdderStart = LAdderEnd;
```

In Azimer's interpretation, the correct C code was supposed to be (although it's in comments):

``` c
//  LAdderStart = ((s64)LAcc * (s64)LRamp) >> 16;
```

I'm not that much of an asm practitioner, so I looked up the IMUL operation here:
http://x86.renejeschke.de/html/file_module_x86_id_138.html

It says for the one-operand IMUL mode:
`- One-operand form. This form is identical to that used by the MUL instruction. Here, the source operand (in a general-purpose register or memory location) is multiplied by the value in the AL, AX, or EAX register (depending on the operand size) and the product is stored in the AX, DX:AX, or EDX:EAX registers, respectively.`

Which means that ecx isn't *= anything or modified, because the result is stored in EDX:EAX and not ECX.  Throughout the entire inline asm, ecx was set to unmodified LAdderEnd and never at all updated, thus causing me to decode the asm as `LAdderStart = LAdderEnd; // ecx` and Azimer to have actually intended it as: `LAdderStart = ((s64)LAcc * (s64)LRamp) >> 16;`, which is not ecx.

If my interpretation so far is correct here, then maybe this could have anything to do with an audio HLE bug in some games using ABI1?  Or is my interpretation wrong?  Again not that much of a regular asm guy, so wanted to make sure before I decide how to merge the two C paths together in the next commit to resolve the confusion.

**Comment by Azimer** [comment]
The commented out code is likely correct.  ENVMIXER needs to be looked at for sure.  It was 100% accurate to RSP but at some point I ended up introducing a regression trying to optimize.  This should not hold back your PR.  If your C variant is like the assembler code, go with what you have.  We can deal with whatever regression comes out of it when we go over the ENVMIXER again to fix Golden Eye 007.

**Comment by cxd4** [comment]
Right, that seems a good idea.  I'll leave the commit as-is with the "bug" in it and wait until after the pull request to look at correcting it, hopefully once I can find a game it fixes or something.

**Comment by Azimer** [comment]
I reviewed this closer and the old ASM code appears bad.  I will be making a change to use the older C version.  I believe I made a faulty assumption when I was much younger.
