### ISSUE TITLE
Force Old Audio Sync doesn't work in the DirectSound plugin

### ISSUE THREAD

**Issue by Cetacea3691** [Azimer/AziAudio#123]
Can any one else also confirm this ?

**Comment by Azimer** [comment]
Not necessarily a bug at this point.  The code is being revised and will be reimplemented.

**Comment by Cetacea3691** [comment]
Ah okay :)

**Comment by Azimer** [comment]
I plan to deprecate Old Audio Sync.  I won't fix this.
