### ISSUE TITLE
Temporarily disable Prevent Buffer Overruns when the Frame Limiter is disabled

### ISSUE THREAD

**Issue by oddMLan** [Azimer/AziAudio#125]
https://github.com/project64/project64/issues/589
Hi, I (mistakenly) made this issue for Project64 originally.

Having PBO enabled with the frame limiter disabled would be kind of useless, since the audio sounds distorted at high speed anyway :P
It would be more useful in order to be able to speed up the game without having to sacrifice Fixed Audio Timing with this plugin, or Prevent Buffer Overruns (since without this option, the audio is more prone to crackle).

Is there a way to know for the audio plugin that the frame limiter has been disabled?
If not, I guess @project64  will have to do some code changes to the plugin spec to integrate this feature seamlessly.

Or alternatively like @cxd4 suggested, we can keep PBO enabled and disable FAT when the frame limiter is disabled (but that would be a change Project64 would have to implement).

But since FAT is required for some timing-sensitive games like Simcity 64 (afaik, without FAT and AI = 0 the game crashes) I guess the first approach would be preferable, but depends which one is more doable taking in account the emulator/plugin limitations.

**Comment by cxd4** [comment]
I can say already that there probably can be no way for the audio plugin to "know" whether the speed limiter is disabled.  I'm no AI expert on the timing threads or anything, but that seems fairly second knowledge to me.

I think the most convenient thing for everyone would be if there was a way to modify _Prevent Buffer Overruns_ within AziAudio's side such that you could freely hit F4 or whatever to disable the speed cap and not still be throttled to 60 VI/s.  However, I'm skeptical that there is any possibility of doing that either.

**Comment by Azimer** [comment]
I think I'd rather have PBO as a disabled option by default allowing the emulator to drop excess buffers by default.  PBO doesn't kick in under normal circumstances.

**Comment by Azimer** [comment]
Unless there's suggestions on how to implement this without changing the spec, I am going to close the issue.  The new configuration changes since 2015 should allow for you to disable PBO permanently.
