### ISSUE TITLE
DirectSound plugin crashes after switching games in Project64 2.2

### ISSUE THREAD

**Issue by LegendOfDragoon** [Azimer/AziAudio#126]
While running a game, it crashes after switching to another game.

**Comment by oddMLan** [comment]
Which build? Using 2.2.0.538 here. Doesn't crash for me

**Comment by cxd4** [comment]
...Wait, what?

The forum buildbot at pj64 doesn't include AziAudio as part of the Project64 package (...does it?).

**Comment by oddMLan** [comment]
**Can confirm.**
Ignore what I had written previously, my bad, I thought this was the PJ64 repo

**Comment by Frank-74** [comment]
All the initialize/deinitialize are now in Soundriver.  AI_ResetAudio() and AI_Shutdown() are likely culprits for the crashing.  I'd probably remove all the conditions and just set the isinitialized  to what it should be on exit.

**Comment by cxd4** [comment]
I don't usually test the DirectSound build nowadays.

Is there any crashing with the XAudio2 or is it just the deprecated DirectSound part we have crashes to worry about that I should check?

**Comment by oddMLan** [comment]
No, there's no crashing with the XAudio2 version

**Comment by Frank-74** [comment]
Fixed it I think.

In main.cpp, change 'cpp snd->AI_ResetAudio(); in RomOpen() to snd->AI_Startup(), and in RomClosed() to snd->AI_Shutdown()

**Comment by LegendOfDragoon** [comment]
Problem is that other emulators do not use RomOpen for Audio, so while your solution may work in 2.x, it will not work in Project64 1.6 or other emulators.

I tried seeing if I can figure out a solution that works on all emulators, but I can't think of anything w/o making too many changes.

**Comment by Frank-74** [comment]
This seems to work with 1.6 as well.
https://github.com/Azimer/AziAudio/compare/master...Frank-74:master

**Comment by LegendOfDragoon** [comment]
Good job on figuring out an easy solution. All you need to do is implement this https://github.com/Azimer/AziAudio/compare/master...Frank-74:master#diff-e9946ef4c829982b07e05ee5a63271a1R192

I feel silly not being able to find this easy solution. I debugged the issue earlier, but I'm not too good with C++.

**Comment by Frank-74** [comment]
@LegendOfDragoon You still need to comment out the AI_ResetAudio()'s in RomOpen and RomClosed.  Otherwise a crash happens switching from XA2.  Unknown Memory Action or something.

**Comment by Azimer** [comment]
If someone could come up with a fix everyone is happy with, I'd be more than happy to auto merge it with a PR.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon You still need to comment out the AI_ResetAudio()'s in RomOpen and RomClosed. Otherwise a crash happens switching from XA2. Unknown Memory Action or something.

Problem with commenting out the AI_ResetAudio() in RomClosed is that there is supposed to be some sort of DeInitialization. @Frank-74 Can you elaborate on this XA2 issue? Maybe we can try and find a better solution.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Start game with DS8, when the first sound starts to play, change plugin to XA2.
Error
Unknown memory action
Emulation stopped.

Removing the AI_ResetAudio()'s in RomOpen and RomClosed stops this error.  Haven't noticed any problems with it.

**Comment by Frank-74** [comment]
How about this?

`cpp
EXPORT void CALL RomOpen(void) 
{
	if (snd != NULL)
	{
		Dacrate = 0;
	}
}

EXPORT void CALL RomClosed(void) 
{
	if (snd != NULL)
	{
		Dacrate = 0;
		snd->AI_Shutdown();
	}
}
```

**Comment by Frank-74** [comment]
For a more thorough solution, maybe add EXPORT void CALL PluginLoaded(void).  I've noticed Jabo's uses PluginLoaded, as does Glide and the RSP in PJ64.

**Comment by LegendOfDragoon** [comment]
>@LegendOfDragoon 
Start game with DS8, when the first sound starts to play, change plugin to XA2.
Error
Unknown memory action
Emulation stopped.

I can't seem to reproduce, although to be fair, I may have changed code and forgot about it. So what I suggest is that you send a PR that just adds this line https://github.com/Azimer/AziAudio/compare/master...Frank-74:master#diff-e9946ef4c829982b07e05ee5a63271a1R116

Then once that PR is merged, I'll download latest source and try again. Maybe then, we can find a good solution for the XA2 issue.

>For a more thorough solution, maybe add EXPORT void CALL PluginLoaded(void) for reset, instead of deinit/init again. I've noticed Jabo's uses PluginLoaded, as does Glide and the RSP in PJ64.

I'd rather not rely on functions that only work in newer spec.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Just built both XA2 and DS8 versions from the master branch.  No sound after switching from DS8 to XA2.  The AI_ResetAudio() in RomOpen is the cause.

**Comment by LegendOfDragoon** [comment]
@Frank-74 so I take it, you don't see the crash anymore? I think the initialization code in the XA2 version needs some work.

**Comment by Frank-74** [comment]
@LegendOfDragoon No crash.  It initializes in main on ```cpp EXPORT Boolean CALL InitiateAudio(AUDIO_INFO Audio_Info) ```

**Comment by Frank-74** [comment]
@LegendOfDragoon 
Update:
I get the unknown memory action error when adding your STREAM_DMA experiment.  Changing from DS8 to XA2.

Had a look at how RomOpen/RomClosed compile with both having AI_ResetAudio.  Bit odd them both having the same entry point.
```
Exported fn(): RomClosed - Ord:000Ch
Exported fn(): RomOpen - Ord:000Dh
:10001AD2 8B0D88830110            mov ecx, dword ptr [10018388]
:10001AD8 85C9                    test ecx, ecx
:10001ADA 740C                    je 10001AE8
:10001ADC 83259083011000          and dword ptr [10018390], 00000000
:10001AE3 E9C2060000              jmp 100021AA

* Referenced by a (U)nconditional or (C)onditional Jump at Address:
|:10001ADA(C)
|
:10001AE8 C3                      ret
```
