### ISSUE TITLE
How should we clean the repository root files up?

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#129]
Now that AziAudio compiles and runs on Linux (no sound), I start to want to upload a new shell script called `make.sh` (also builds on Windows too if you execute it through Git/MSYS shell).

However as Azimer noted we have quite a plentiful lot of build script/project files in this repository already, and I am starting to want to move some of them somewhere.

The VS2013 solution is the only one Azimer uses IIRC and is recommended for Windows builds.

Maybe we could clean the root workspace of the repo by moving these files:
* make_wdk.cmd (my WinXP-64-bit-compatible build script to use MSVCRT.DLL)
* mingw-build.cmd (SwooshyCareb's modern, more complex MinGW build script)
* make.sh (not yet uploaded--my Unix shell script to compile on *nix-based systems)
* possibly the Xbox solution @weinerschnitzel contributed??

The fastest way to move all of these out of the root index of the repo, without creating a new directory, would be to put them under "3rd Party" I guess.

I can take care of this for the first 3 files (don't have Xbox/MSVC 2002 so can't test the 4th) by myself but would like anyone's opinion or at least @Azimer's on where this stuff could be moved to?

PropertySheets...zilmar is starting to wonder what to do with those in case he starts to think that separate repositories can help port Project64 easier.  (They may have to be changed/deleted.)

**Comment by weinerschnitzel** [comment]
Maybe instead of moving the project files and build scripts to "3rd Party," how about we put them in a "Make" folder, and use another folder "Platform" to hold API specific headers/libraries and Xbox stubs?

**Comment by cxd4** [comment]
Yeah "Make" sounds fine.

In the short term I wondered otherwise because atm we'd be moving 2 or 3 files and creating 1 folder.

>and use another folder "Platform" to hold API specific headers/libraries and Xbox stubs?

Well if we did that wouldn't this contradict the existing "3rd Party" folder which zilmar added?

**Comment by weinerschnitzel** [comment]
It would be the same folder, I just feel that renaming it to "Platform" would make more sense.

**Comment by cxd4** [comment]
I would have named it to something different than "3rd Party" too (at least without spaces), but this was the directory that zilmar chose and it was easier for us to match what was forward-compatible with what he was going to fork.  (If we do change that, it will collide with the rest of the PJ64 plugin/projects' setups.)

Besides it contains the DirectX headers and stuff...it's maybe described as "Platform" but I think the point is they're external to the AziAudio HLE codebase, so 3rd Party.

**Comment by Azimer** [comment]
Maybe all the build stuff should be in a "BUILD" folder.  It's hard for me to transition from something specific to VS2013 but if this plugin could become platform independent without too much trouble, I'm okay with change.  As long as I can double click the sln file and it pops up in the IDE without complication. :)

**Comment by cxd4** [comment]
Sounds good.

Based on other votes, now I think no longer to move them to "3rd Party" but to create a new folder for the non-VC2013 build scripts--either "Build" or "Make" as weinerschnitzel suggested.

The only reason I'm leaning more towards "Build" is because if I make the new folder named "Make", it suggests that the Linux `Makefile` that @SwooshyCueb added would be moved there as well.  Though I think that the "Makefile" file is traditionally kept in the root directory, plus I don't know how to update that file to fit under there anyway.

So considering all of that, I'll name it "Build" as Azimer proposed and welcome anyone else to change the folder name if they prefer a different idea.  Atm I'm just trying to get the Unix script uploaded one way or the other; anyone feel free please to change.

**Comment by cxd4** [comment]
So far the matter seems decided as of the PR having been merged.

Again if anyone else wants to revisit this I'd be happy to reopen if others prefer different.

**Comment by Azimer** [comment]
I am content with that decision.  If someone is opposed they'll speak out... hopefully with a contribution to the issue or PR with a discussion on their change. :)
