### ISSUE TITLE
An unusual case of clamping in ABI3mp3

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#13]
https://github.com/Azimer/AziAudio/blob/38eacfcee45dfb809c8838440245cff388f7eaa2/AziAudio/ABI3mp3.cpp#L574 Maybe more of a question, not an issue necessarily.

I can't help but wonder why it clamps underflow to only -32767, not -32768?
Because RSP hardware itself is not capable of doing this even...at least not directly, using the VU.

It was the one and only part of the source I could not install my `pack_signed` function to in my PR.

**Comment by LegendOfDragoon** [comment]
Looks like human error. Probably should be -32768. Nice find.

**Comment by Azimer** [comment]
Go ahead and camp to -32768.  I don't believe you will see a difference in audio going from -32767 to -32768.  I will take a peek at my original REing and see if i can determine why I did 767.

**Comment by cxd4** [comment]
[closed just because it was merged... can reopen if it's discovered there was a reason for -32767]
