### ISSUE TITLE
Mario Party

### ISSUE THREAD

**Issue by weinerschnitzel** [Azimer/AziAudio#137]
Audio is too fast. Not sure if it's the same issue as #4 but I figure I would report it anyway. Tested using DS8 plugin on PJ64 1.6 and PJ64 2.3 Git. I haven't had much luck building the XA2 plugin yet. Not getting sound with Super Mario 64 and Mario Party just crashes. Using PJ64 1.6 and 2.3 Git. I'm unsure if the vs140_xp tool set is giving me issues because I am using VS2015 on Windows 10 to build. If anyone has advices, please chime in. :)

I find Mario Party an interesting case in terms of AI emulation. On the XBox, old JttL 1.2 sounds fine, when my quasi-zilmar spec versions of bsmiles' RSP and sister SDL audio plugin have missing notes in the intro.

**Comment by LegendOfDragoon** [comment]
Yes, it's essentially the same issue, but feel free to keep the issue open. I made an experimental branch that tweaked the ds8 code a bit. Feel free to test that out.

**Comment by weinerschnitzel** [comment]
You're experiment with GetReadStatus does in fact fix this issue. I believe you were talking about this experiment with Frank-74 earlier so I'll have to find that thread to read more. What is keeping you from submitting it as a PR?

**Comment by LegendOfDragoon** [comment]
@weinerschnitzel It might need more tweaking and it does need more testing.

**Comment by Azimer** [comment]
Is this still an issue?

**Comment by Azimer** [comment]
Closing this issue
