### ISSUE TITLE
Volmue slider no longer works.

### ISSUE THREAD

**Issue by Yui12** [Azimer/AziAudio#143]
After starting a game and trying to lower the volume, the slider doesn't seem to be doing anything to lower the volume. Using the latest git of Project 64, and the latest git of aziaudio.

**Comment by cxd4** [comment]
Yeah I've noticed this for a few months now.

I guess I never felt like reporting this because it seems unique to the DirectSound build only, and some of us have an interest in replacing DirectSound with something else (possibly like OpenAL).  With the newer XAudio2 driver code built for the plugin though, IIRC you shouldn't have this issue.

**Comment by Yui12** [comment]
For whatever reason the options for playback device is greyed out along with audio logging and shortcut keys. Here is a picture.

![untitled](https://cloud.githubusercontent.com/assets/13986398/12464173/9415351c-bf7c-11e5-9915-c916f37dbbe8.png)

**Comment by vgturtle127** [comment]
@Yui12 @cxd4 I thought OpenAL wasn't being actively developed anymore? I didn't think even OpenAL Soft was being developed anymore?

XAudio2 is usually better in my experience.

**Comment by Yui12** [comment]
Can someone be nice enough to compile a version that has xaudio2 as the default for me to get around this problem right now?

**Comment by budtz** [comment]
i also have this problem

**Comment by Yui12** [comment]
Well I don't expect it to be fixed at this rate though.

**Comment by budtz** [comment]
i get grayed menues as well. does it mean i cant use xaudio?

**Comment by Frank-74** [comment]
Backend is not selectable from the plugin.  All those greyed items are not in the plugin.  Last time I compiled, XAudio2 was the default build, to build the DS8 version you needed to add XAUDIO_LIBRARIES_UNAVAILABLE to the build definitions.

Here is my compile of both XA2 and DS8 versions.
https://dl.dropboxusercontent.com/u/9498358/n64/AziAudio0.7WIP6.zip

**Comment by Yui12** [comment]
Thanks but the XA2 version works on 2.3 for me, but I'm using a build from a few months ago. I tried the back ends and the problem still exists. Muting it doesn't even work either.  Doesn't really matter to me anymore since Jabo with the new timing works better that the audio on 1.6.

**Comment by budtz** [comment]
Thx. I still cant save settings in them thou and I need for all gaming to turn volume way down to match audio levels of things like tv movies. Jabu works thou as long as newer than 2.2. 

I get quite bad input lag with P64 compared to retroarch. I was hoping changing plug-ins could help but it couldt.

**Comment by cxd4** [comment]
Still need to implement SDL so I can stop being unable to run this plugin on different systems.

It also has a very straightforward volume control function.

**Comment by budtz** [comment]
changlog says this is fixed but it still dosnt work

**Comment by Frank-74** [comment]
I fixed it for DS8 version.  Forgot to edit the XA2 driver to fix the volume setting.
The settings are saved in both versions, but the XA2 volume isn't being set.
Try my DS8 version: https://www.dropbox.com/s/s4f9eju891l0zxt/AziAudioDS8.dll?dl=1

**Comment by Frank-74** [comment]
@budtz 
Fixed it now, PR here to see changes: #157.

**Comment by Yui12** [comment]
Excellent. Appreciate the work here. Now I don't have to turn down the whole emulator when using this plugin through windows volume mixer. I tested it it and seems to work alright. Thanks again for fixing this.

**Comment by oddMLan** [comment]
I think you accidentally this issue

**Comment by Yui12** [comment]
I closed it, but I changed my mind to reopen it quickly just in case it doesn't work for everyone.

**Comment by Yui12** [comment]
Alright, now it's safe to close it. Should be no problems now.

**Comment by cxd4** [comment]
Another way to control the volume is to break audio LLE while optimizing the RSP plugin.  Works especially well when I wear headphones turned all the way up.
