### ISSUE TITLE
Twisted edge extreme snowboarding: no sound

### ISSUE THREAD

**Issue by olivieryuyu** [Azimer/AziAudio#145]
Can it be fixed? Even with à Hack?

**Comment by LegendOfDragoon** [comment]
Which problem are you referring to, exactly? Gameshark code can already get sound. Although it doesn't sound as good as a modified 1964 audio plugin, iirc.

I don't think that gameshark code completely fixes the sound.

**Comment by olivieryuyu** [comment]
really? a GS code? never heard about this. Can you share it with me?

and there is a modified 1964 audio plugin have sound with this game? never heard about it

Where i can get it?

Anyhow would it be possible to get the same functionality in Azi plugin? :)

**Comment by cxd4** [comment]
I do not know when, where and by whom, but it was added to Project64 CHT.
https://github.com/project64/project64/pull/910

Granted I have not tested it yet as I am not running Windows so can't run Project64 yet, but feel free to test that to see if that helps you out.

**Comment by LegendOfDragoon** [comment]
@olivieryuyu you can read about the issue here https://github.com/project64/project64/issues/466 .

>and there is a modified 1964 audio plugin have sound with this game? never heard about it

With the gameshark cheat, any audio plugin should have sound for that game. You'll need to turn on fixed audio timing, because it sounds worse without it for this game.

With 1964 audio, you just need to modify the buffer size to 0x800 in order to get good audio in Boss Studios games. Basically any audio plugin similar to zilmar's audio should work decent for Boss Studios games, but most of them have certain issues, which is why I'm currently experimenting to improve the results. I can release my audio plugin (which is based on different source codes) once I figure out how to solve certain things.

>Anyhow would it be possible to get the same functionality in Azi plugin? :)

He would need to change some code to get better audio in Boss Games. I'm not exactly sure how to do that without just copying zilmar's method for audio.

One key issue with Fixed Audio Timing for Top Gear Rally and Twisted Edge if that if you pause the emulator or briefly have a slowdown in performance, the audio gets messed up. Although, this issue affects other games too. One workaround is to briefly disable frame limiter (even 2-3 seconds should be good enough). If you're using a fast video plugin it shouldn't happen too often if you never pause the emulator. High performance is essential.

**Comment by Azimer** [comment]
The "streaming" option works best for BOSS games but somewhere along the lines it stopped working.  I'm still lurking about waiting to start working on this again once this massive database project is completed... we are on month 8. :(

**Comment by Azimer** [comment]
Circling back on this -- The DirectSound plugin in the current source uses "Streaming" audio.  I just tried the cheat in Project64 and it works.  I am curious why it works and what isn't being done correctly?  Has anyone looked into it further in recent times?

**Comment by cxd4** [comment]
I heard it works in some continuation of UltraHLE as well, but I hadn't checked it.

**Comment by LegendOfDragoon** [comment]
>Has anyone looked into it further in recent times?

Not really. I was just happy to get sound at all, so I left it at that :smile: . I don't really have any ideas for debugging. Although I suspect that testing the gameshark code on console might give some clues.

**Comment by Frank-74** [comment]
I never knew of this cheat fix before now.  Just tried it.  Sound is intermittent.  It becomes progressively more chopped as time goes on.

Is the cheat fix creator the same person that discovered the indy/naboo fixfpulocations?  I think he now goes by the name Ghost.  Clever guy.

**Comment by LegendOfDragoon** [comment]
>I never knew of this cheat fix before now. Just tried it. Sound is intermittent.  It becomes progressively more chopped as time goes on.

You can try Azimer's 0.30 and put buffer size on minimum, or Shunyuan's audio plugin (with tweaked buffer size), for better audio in this game + Top Gear Rally with FAT on.

**Comment by Frank-74** [comment]
> Azimer's 0.30 and put buffer size on minimum.

Or I can put in a slider in Azimer's 0.7 for buffer size!  Will be something interesting to do while I have the flu.
Poetic too :)

**Comment by Azimer** [comment]
The current source works too.  You need to use the DirectSound variant.

**Comment by Frank-74** [comment]
I just built the current DirectSound variant.  It sounds better for this game, but not for games like TWINE.  It also has the volume bug.  I fixed it in my build of the XA2 plugin.  When switching plugins it loses volume/goes silent.  I have to look at what I did to fix it and submit a PR.  Try my hack of your XA2 plugin to test against the DS8 version.  Switching plugins from/to DS8/XA2.  DS8 plugin loses audio, XA2 never loses audio with the fix.
My hack of 0.7 XA2 here: https://www.dropbox.com/s/9wv7nohyiz24mtf/AziAudioXA2.dll?dl=1
Config saves the audio sync and volume setting in Project64\Config\AziCfg.bin.

**Comment by cxd4** [comment]
>I think he now goes by the name Ghost. Clever guy.

It happens when anyone deletes their GitHub account.  mudlord, exhalatio, "AIO" before he made his LegendOfDragoon account alt, are all now "Ghost".

**Comment by cxd4** [comment]
Having the flu sucks major ass.  I'm lucky I was even able to fake it enough to get a job while I still was sick with it.  Those "C-Boost" Bolthouse Farms fruit juice drinks are pretty good at overdosing on enough zinc, calcium, and vitamin C to suppress the flu...vitamin water also works but is kinda dumb, may as well just buy pure zinc.

**Comment by Azimer** [comment]
Get better soon!

**Comment by Frank-74** [comment]
I drank a bottle of something called ManFlu.  It's a massive dose of vitamins, mainly vitamin D.  Apparently vitamin C doesn't do much for a cold or flu, it's vitamin D.

**Comment by cxd4** [comment]
Yeah vitamin C by itself is pretty weak.  I've found that a combination of vitamin C with zinc and calcium is good.  Zinc itself was primarily enough to make my mom feel better right away, but it never had that effect with me for some reason.  We were sick with the exact same thing.

No idea about vitamin D.  The organic whole-foods orange juice I buy has two Vitamin B's in it...Monster Energy drink from America is pretty good at overdosing on all forms of Vitamin B and knocks headaches and cold symptoms right out for me.

**Comment by Azimer** [comment]
Can anyone give me a quick primer on how these cheats work in PJ64?  
Cheat6="exhalatio audio hack",81051840 AD99
For example.  Does it write 0xAD99 to 0x81051840 on an interval?  I'd like to create a game specific hack as an option in the config for Twisted Edge only.

**Comment by LegendOfDragoon** [comment]
@Azimer , the trick is to change AI_DRAM_ADDR_REG . Normally it always = 0x003F2000 in Twisted Edge. The game writes sound to another area in memory (at least on emulators, not sure about console), so you change AI_DRAM_ADDR_REG.

On the plugin's side, you can set AI_DRAM_ADDR_REG to 0x003F4000 for Twisted Edge.

I'd like for someone to try that GS code on console to see what happens.

**Comment by theboy181** [comment]
I'll do it with you this weekend.

**Comment by Azimer** [comment]
Thanks @LegendOfDragoon .  I got this change in, hopefully general enough to catch the others.  It seems I am able to grab the first address sent then each consecutive length stays at that fixed address.  This should be sufficient until it can really get looked at.

**Comment by Azimer** [comment]
Completed in master using a hack.
