### ISSUE TITLE
Issue to discussion / ramble thoughts on the new configuration branch

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#15]
Add a new configuration to move us away from binary files.  My thoughts so far:

* Use JSON file format for configuration and multi-ROM configuration.
* Using RapidJSON
*

**Comment by cxd4** [comment]
I don't know anything about JSON myself but wouldn't mind starting off implementing a traditional C text API like what z64gl uses for multi-ROM text-based config.

That is to say until someone who knows more about standardized higher-level config APIs can recycle that in over primitive handmade stuff like that.  But I'd be happy with either; I just don't have the experience or know-how of both.

**Comment by Azimer** [comment]
Configuration is committed to master
