### ISSUE TITLE
Pokemon Stadium 2 GB Tower doesn't work in HLE

### ISSUE THREAD

**Issue by LegendOfDragoon** [Azimer/AziAudio#152]
It just freezes every time I try to run the game.

**Comment by cxd4** [comment]
Does it freeze with audio LLE as well?

I'd like to debug the issue but need to work my way up to getting myself a personal computer with internet first.  Not really going to test N64 emulation out on a bunch of public computers with Windows put on them. :)

**Comment by LegendOfDragoon** [comment]
I initially tried HLE. It boots in LLE, so I guess it seems to work fine, although the audio is bad.

**Comment by Azimer** [comment]
Never tested this game before.  For clarity, what is "GB Tower"?

**Comment by Frank-74** [comment]
@Azimer 
Here's a video.
https://www.youtube.com/watch?v=h_FBw04f9gg

Looks like a Game Boy emulator on the N64, playing the gameboy version of Pokemon Stadium 2.
Here's another video showing how to "Connect GBC roms with Project64".

**Comment by cxd4** [comment]
GB Tower is some transfer pak thing that a bunch of Pokémon fans care about, or if you're vgturtle.

It's been found to use custom RSP microcode (with scalar-only instructions, no use of the vector registers at least with that class) when someone initiates a room in Pokémon Stadium.  Nobody ever sent me a save state to test it, though, so I never analyzed the microcode.

**Comment by Azimer** [comment]
I believe this issue needs to go back to the emulator itself.  Clearly there's an issue separating HLE audio lists with this GB transfer pack.  I am going to close the issue in a couple weeks if I hear nothing else.
