### ISSUE TITLE
AddBuffer should write 8 bytes?

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#158]
According to docs here: http://hcs64.com/files/n64-hw.dox, length of buffer must be multiple of 8.

So should we write 8 bytes instead of 4, like this?
```cpp
	for (DWORD x = 0; x < length; x += 8)
	{
		bufferData[writeBuffer][x] = start[x + 2];
		bufferData[writeBuffer][x+1] = start[x + 3];
		bufferData[writeBuffer][x+2] = start[x];
		bufferData[writeBuffer][x+3] = start[x + 1];
		bufferData[writeBuffer][x+4] = start[x + 6];
		bufferData[writeBuffer][x+5] = start[x + 7];
		bufferData[writeBuffer][x+6] = start[x + 4];
		bufferData[writeBuffer][x+7] = start[x + 5];
	}
```

**Comment by Azimer** [comment]
This won't have any impact on accuracy.  With the new audio code coming in, I don't see this getting changed.

**Comment by cxd4** [comment]
Frank what's the original/current code in reference here?

**Comment by Frank-74** [comment]
@cxd4 Under the addbuffer function here: https://github.com/Azimer/AziAudio/blob/master/AziAudio/XAudio2SoundDriver.cpp#L183

**Comment by cxd4** [comment]
Ah, I see.

It's basically the same exact result functionally, as long as `length` is aligned such that the 3 LSBs are 0.

So the original ...
```c
for (DWORD x = 0; x < length; x += 4)
{
	bufferData[writeBuffer][x] = start[x + 2];
	bufferData[writeBuffer][x+1] = start[x + 3];
	bufferData[writeBuffer][x+2] = start[x];
	bufferData[writeBuffer][x+3] = start[x + 1];
}
```
... simplifies to ...
```c
for (DWORD x = 0; x < length; x += 4)
{
	bufferData[writeBuffer][x + 0] = start[x + (0 ^ 2)];
	bufferData[writeBuffer][x + 1] = start[x + (1 ^ 2)];
	bufferData[writeBuffer][x + 2] = start[x + (2 ^ 2)];
	bufferData[writeBuffer][x + 3] = start[x + (3 ^ 2)];
}
```
... which simplifies again to ...
```c
for (size_t x = 0; x < length; x++)
	bufferData[writeBuffer][x] = start[x ^ 2];
```

I can PR this myself in a bit.  Jumping by 8 could be optimized with some SSE shuffling as well as conforming to the doc you mentioned; I'll decide later when I get home.

**Comment by Azimer** [comment]
start is an 8bit pointer not 16bit.  So using ^2 won't work unless you cast it
```C
for (size_t x = 0; x < length/2; x++)
	((u16 *)(bufferData+writeBuffer))[x] = ((u16 *)start)[x ^ 2];
```
I looked at the source this would modify.  This code is legacy and will be deprecated.  Any change done here won't be overwritten and may be reused elsewhere.

**Comment by cxd4** [comment]
I understand they are both 8-bit pointers, but the fact remains that the pattern you are swapping is strictly 16-bit little-endian.  You would still need to ^ by 2.

Maybe what you're not seeing is you're already doing a ^ by 2.

You have this right now:
```c
for (DWORD x = 0; x < length; x += 4)
{
	bufferData[writeBuffer][x] = start[x + 2];
	bufferData[writeBuffer][x + 1] = start[x + 3];
	bufferData[writeBuffer][x + 2] = start[x];
	bufferData[writeBuffer][x + 3] = start[x + 1];
}
```

start[x + 2] is the same thing as start[x + (0 ^ 2)].
start[x + 3] is the same thing as start[x + (1 ^ 2)].
start[x] is the same thing as start[x + (2 ^ 2)].
start[x + 1] is the same thing as start[x + (3 ^ 2)].

So the only reason your code works is that you are doing ^ by 2.

The simplified result should be the final loop I posted.  Yes it's deprecated, but this conversation is proof it was confusing.  I feel like changing it; pity I can't test XAudio on Linux.

**Comment by Azimer** [comment]
You are right though it doesn't prove that it's confusing. :)  It's been so long since I messed around with this stuff I was confusing myself.  The 8bit pairs are already little endian but be "word swapped" to reverse the channels.

**Comment by cxd4** [comment]
It's all under the #ifdef LEGACY_SOUND_DRIVER stuff anyway, so as long as you're sure that's all to be taken out ultimately it doesn't matter.

It may not be confusing in the sense of misrepresentation, but the unsimplified way of writing it implies the lack of a pattern, which I was able to spot without having written the code myself.

It's only invoked through AiLenChanged in main.cpp which always passes the 64-bit aligned decode of AI_LEN_REG, so it always writes a multiple of 8 bytes, as implied by what Frank linked to.
