### ISSUE TITLE
ENVMIXER_GE():  unused initialized variable `AuxIncRate`

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#172]
This is one of two final remaining warnings I wasn't able to fix in the last PR.

See also:  https://github.com/Azimer/AziAudio/issues/171

```
./../AziAudio/ABI_Envmixer.cpp: In function 'void ENVMIXER_GE()':
./../AziAudio/ABI_Envmixer.cpp:314:6: warning: variable 'AuxIncRate' set but not used [-Wunused-but-set-variable]
  u16 AuxIncRate = 1;
      ^
```

**Comment by Frank-74** [comment]
I wonder if it's related to the Goldeneye bug reported in #5 .

I discovered that the left/right was reversed for Goldeneye.

It defines the AuxIncRate variable the same in void ENVMIXER(), but has a later condition testing the value:
```cpp
	if (AuxIncRate) {
				aux2[MES(ptr)] = pack_signed(aux2[MES(ptr)] + MultQ15(/*(a2*0x7fff)+*/(s16)i1, (s16)AuxR));
				aux3[MES(ptr)] = pack_signed(aux3[MES(ptr)] + MultQ15(/*(a3*0x7fff)+*/(s16)i1, (s16)AuxL));
}

**Comment by Azimer** [comment]
I don't believe it's related.  I no longer have any of my original reverse engineering code to check back with.  I'd have to redo everything which may not be a bad idea someday if I want to make HLE audio more accurate.

**Comment by cxd4** [comment]
The warnings are kind of good to have though since they add some color to my otherwise completely monochrome terminal screen.  Yay for colors!

http://i.imgur.com/gx55T5R.gif

**Comment by Azimer** [comment]
Frank was right.  After leaving the issue on the floor for awhile and looking back at it, it's exactly the issue.  However, I am removing the variable anyway and checking the flag mask instead.  I will bring both methods in line when I do an HLE cleanup once I am done with the main plugin.
