### ISSUE TITLE
HLE volume problem

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#178]
HLE volume mix is wrong.  Affects lots of games.

Here is example of Road Rash 64, HLE and LLE to compare.
https://www.dropbox.com/s/izqhfcxq92tkpok/RoadRashHLE.wma?dl=1
https://www.dropbox.com/s/shhq3h6lc67bs33/RoadRashLLE.wma?dl=1

Rubbish sound recorder in Windows 8.1, only records at 96Kbps bitrate, so quality is bad, but you get the idea.

**Comment by LegendOfDragoon** [comment]
By any chance were you loading a savestate?

**Comment by Frank-74** [comment]
Nope.

Edit game settings, selected XA2 plugin, checked HLE audio, start game, record audio, end emulation.
Edit game settings, unchecked HLE audio, start game, record audio, end emulation.

**Comment by Frank-74** [comment]
Other games with very noticeable HLE dry/wet mix problems.
BattleTanx : The "3do" speech is very quite compared to following music at startup.
BattleTanx - Global Assault : Music has echo effect which overpowers dry signal, same as Road Rash.
Castlevania - Legacy of Darkness : Breathing sounds missing, and lots of sounds missing, volumes totally wrong.  Example of the start intro here:
https://www.dropbox.com/s/gtmioxayqgsqyu3/CastlevaniaLOD-HLE.wma?dl=1
https://www.dropbox.com/s/ri32i1go8vjfbls/CastlevaniaLOD-LLE.wma?dl=1

**Comment by cxd4** [comment]
>It would be very useful to get audio logging to work in the plugin.

I would be happy to implement that once I am able to run the plugin.

Also, for some reason those Dropbox links don't let me play the audio in-line through the browser.  I have to download both of them as files to play them locally.  th;dd

**Comment by Frank-74** [comment]
>Also, for some reason those Dropbox links don't let me play the audio in-line through the browser. I have to download both of them as files to play them locally. th;dd

I've just downloaded and installed Audacity, re-recorded, and saved as mp3, they now play in browser.
https://www.dropbox.com/s/3s4ay28abjwyyy9/CastlevaniaLOD-HLE.mp3?dl=0
https://www.dropbox.com/s/5j3l5lb9wdm476p/CastlevaniaLOD-LLE.mp3?dl=0

**Comment by vgturtle127** [comment]
@Frank-74 Even LLE doesn't sound right to me, though. 😢

**Comment by Frank-74** [comment]
> Even LLE doesn't sound right to me, though. :cry:

Jabo's to compare with.
https://www.dropbox.com/s/5gnyky2mr5dsuoh/CastlevaniaLOD-Jabo.mp3?dl=0

**Comment by LegendOfDragoon** [comment]
@Frank-74 I'm not sure why HLE sounds so awful on your end. I can't really tell a difference on my end, but I personally wouldn't solely rely on a hearing test for HLE audio.

**Comment by vgturtle127** [comment]
@Frank-74 Huh, maybe it's just me. I just don't remember the audio fluctuations being that up and down towards the beginning of the audio playing. I guess I was wrong.

**Comment by Frank-74** [comment]
XA2 HLE
![castlevanialod-hle](https://cloud.githubusercontent.com/assets/11056843/22867204/6339d9d4-f17b-11e6-9a99-a7e856869d17.JPG)

XA2 LLE
![castlevanialod-lle](https://cloud.githubusercontent.com/assets/11056843/22867207/6e52fb98-f17b-11e6-9c86-f7cd70f3fbe2.JPG)

Jabo
![castlevanialod-jabo](https://cloud.githubusercontent.com/assets/11056843/22867210/75e9fed8-f17b-11e6-8ac1-88363538d102.JPG)

**Comment by cxd4** [comment]
When I click those the inline Dropbox page loads up saying "An audio error occurred" at the top, with "This file can't be previewed" in the middle.

Must be because I uninstalled PulseAudio or something.  Bah, I'll listen to them later.

**Comment by Frank-74** [comment]
@LegendOfDragoon 
>  I personally wouldn't solely rely on a hearing test for HLE audio.

I do, music was my living for 20 years, teaching, performing, writing and recording.  I have good ears.  I can hear all the different sounds separately in my head, like they are different instruments in an orchestra.

**Comment by Frank-74** [comment]
@LegendOfDragoon @cxd4 @vgturtle127 
This is a recent regression, Castlevania LOD sounds correct in HLE with a week old build.

**Comment by cxd4** [comment]
Yeah, I remember you have like supersonic-hearing ears from previous issues you've found.  You're able to hear bats taking a shit.

Could you isolate which commit began the issue?  I wonder if it's the warning fix I did to get rid of the undefined 32-to-16-bit pointer aliasing operations.

**Comment by Frank-74** [comment]
@cxd4 
>Could you isolate which commit began the issue? I wonder if it's the warning fix I did to get rid of the undefined 32-to-16-bit pointer aliasing operations.

I'll build from before/after that commit soon.

**Comment by LegendOfDragoon** [comment]
>This is a recent regression

Ah ok. I forgot about recent commits.. I was so confused lol.

**Comment by Frank-74** [comment]
@cxd4 Yes, it was that commit that broke it.  I reverted it and it sounds good.
https://github.com/Azimer/AziAudio/commit/e64ae9e0132578810a0c536f33a64b2a9d7b6e86

**Comment by cxd4** [comment]
If you change all of those from ((blah > 16) & 0x0000FFFF) to just (blah & 0x0000FFFF) does it work correctly again?  I was really trying to understand what Azimer was intending with those pointer aliasing hacks.  On some platforms it would be the upper 16 bits (blah >> 16); on others it would result in the lower (blah >> 0).

**Comment by cxd4** [comment]
...oh god.  I hope that wasn't also intended to accomplish halfword byte-swapping.

**Comment by Frank-74** [comment]
@cxd4 No worries, it seems (s16)((k0 & 0x0000FFFF); is ok.  Sounds good with all the >16's removed.

**Comment by vgturtle127** [comment]
@Frank-74 Oh, recent commits broke it. I thought you were saying it was a long-standing issue. I need more sleep. 😆

**Comment by cxd4** [comment]
```c
#include <stdio.h>

#include <stdint.h>
static union {
    uint32_t word;
    uint16_t halfwords[2];
    uint8_t bytes[4];
} shitty_aliasing_test;

int main(void)
{
    shitty_aliasing_test.word = 0x11223344;
    printf(
        "%08X "\
        "(%04X %04X) "\
        "%02X %02X %02X %02X\n",

        shitty_aliasing_test.word,

        *(uint16_t *)&shitty_aliasing_test.word,
        shitty_aliasing_test.halfwords[1],

        shitty_aliasing_test.bytes[0], shitty_aliasing_test.bytes[1],
        shitty_aliasing_test.bytes[2], shitty_aliasing_test.bytes[3]
    );
    return 0;
}
```

Results:
```
bash-4.3$ ./test 
11223344 (3344 1122) 44 33 22 11
```

**Comment by cxd4** [comment]
So *(uint16_t *)&k0 is the same as k0.halfwords[0] if k0 were a union based on MIPS-sized words.

If we were compiling on a big-endian machine like MIPS then my PR would have been the correct commit.  Since Azimer was using implementation-defined behavior with pointer aliasing rules broken for x86 little-endian, it was grabbing the top 16 bits of a little-endian 32-bit word...which really was the low 16 bits in the long run.

So I was supposed to byte-swap the byte-swap to understand what he was doing.

Your PR has the correct behavior.

**Comment by vgturtle127** [comment]
@cxd4 Wouldn't a double byte-swap be what you started with? 🤣 

I love working on Project64, but sometimes it makes my head hurt. Hehe.

**Comment by cxd4** [comment]
C was just reading the s32 in client-native endian.

(k0 >> 16) is the high 16 bits, but memory-wise it's the low 16 bits in byte-wise storage.

It's not a double byte-swap; it was just the result of going through unnecessary memory tangling that made it deficient and confusing to read.

**Comment by vgturtle127** [comment]
@cxd4 Ah, OK.

**Comment by Azimer** [comment]
I didn't read your PR as well as I should have obviously and yes, the audio plugin had always been very cpu/os specific.  I wasn't nearly as careful 13-15 years ago or however long it's been.
