### ISSUE TITLE
Apollo website

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#179]
Had to post here since the issue tracker for Apollo isn't open....

http://i.imgur.com/p1djzQz.png

That website is old and like, hasn't ever worked.  Copyright 2001?  Did it used to work 16 years ago?  Also, if you're only using static content, I would host the website for free on GitHub pages.  It would be something like azimer.github.io/apollo/ or apollo64.github.io depending how it's set up.

**Comment by vgturtle127** [comment]
@cxd4 It worked up until about 2013 or 2014 I think. I remember grabbing most of the files and stuff that was on it, but then a few months later it didn't work.

@Azimer I can help you with gathering some of the files and with the setup and coding and what not if you want. 😄

**Comment by cxd4** [comment]
I seem to remember going to that site in 2008 at the latest.  I don't remember it working back then either.

**Comment by Azimer** [comment]
It did work.  It does need a redo.  Unfortunately, I have never seemed to have the time to even come up with a solid design and art.  That isn't my forte.

**Comment by Azimer** [comment]
Opened the issues in [Azimer/Apollo64](https://github.com/Azimer/Apollo64/issues/) if you are looking to have a discussion.

**Comment by vgturtle127** [comment]
@cxd4 Huh, I distinctly remember going to the site after I started the audit, and downloading all the files. Well, I have a backup of the files, I think, so if anybody needs them I have them.

**Comment by Azimer** [comment]
I have FTP access to the site yet.  I will download it and upload it to a new repository.  It's something I've been intending to do anyway.

**Comment by cxd4** [comment]
Oh, sorry.  I didn't realize the Issues section was up earlier and you'd closed it.

Well technically just because I wanted to browse it but couldn't, I guess it's an issue.  I'll move it.
