### ISSUE TITLE
Audio/Video sync problem.

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#182]
This has been a problem on all versions pre 0.7 as well.  Jabo doesn't have this problem.  Thought I'd better make this issue now, before it's possibly handed over to the PJ64 repository.

Best way to demonstrate the problem is start Goldeneye, goto mission select screen, press A then B to go forward then back.  Press F2 (Pause) in PJ64, and unpause, repeat A and B.  The sound switching pages goes of sync.

Each time you pause and unpause, the sync between audio and video changes.  Audio can be immediate or over a second delayed behind the video.

Or, if you just leave Goldeneye playing for a while, it will drift out of sync over time...

**Comment by Azimer** [comment]
I need more detail.  Are you using the latest commit?  XAudio2 or DS8?  Legacy and New?

**Comment by Frank-74** [comment]
I've not built the latest master.  So haven't tested the new audio code from the last couple of days.  I'll build it now and test again.

But this problem has existed since 0.3 version.  On 0.7 it doesn't matter which backend is used DS8 or XAudio2.

**Comment by Frank-74** [comment]
Just tested latest master, and problem with pause/unpausing seems to be not a problem anymore :) .  Built XA2 version.  FAT is on.

I haven't left Goldeneye playing for very long.  But it used to always happen with pausing/unpausing repeatedly.  Now the max delay is microseconds and consistent.  Noticed a bit of crackle for a split second when unpausing, which never used to happen, but now it seems to stay in sync.

I'd tested the old versions 0.3, 0.56, 0.60, and they all had the same problem.  But now it seems fixed! :)

**Comment by Azimer** [comment]
Yeah you can't compare .3, .56 and .60 with .70+.  A vast majority of the code has been changed.

**Comment by Frank-74** [comment]
WIP 7 is a vast improvement over WIP 6.  Based on the little bit of testing I've done the past 20 minutes.

I have left Goldeneye playing for 20 minutes or so, and no problems so far.  Only thing I notice, every now and again, after a while, the audio will stutter.  But with no crackles.  It's like a record skipping every now and then, for a split second.  It's not a problem, and is hardly noticeable.  The sort of thing you only notice when made aware of it.

**Comment by Azimer** [comment]
I noticed that too somewhat.  Usually with FAT enabled.  I think I need to tweak FAT a bit.  The timing isn't quite right.  However, I decided it'd be better to hold a buffer if I can't fill it completely.  This will result in a 60th of a second "pop" rather than a crackle as the game struggles to recover.
