### ISSUE TITLE
Very slow with PJ64 "Sync using audio" option.

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#184]
Tested with latest master.  Turning on Sync using audio in Project64, causes VI's to drop dramatically (15 in Goldeneye), and eventually PJ64 stops responding and I have to close it with task manager.

**Comment by Azimer** [comment]
I have no idea how that is implemented.  I imagine turning on sync in Project64 as well as having either of the two options set in AziAudio will cause a conflict.  Trying turning off Prevent Buffer Overruns and Force Old Audio Sync.  Those are the only two options that stall the emulator to help bleed off some of the audio buffer.

**Comment by Frank-74** [comment]
I have all the sync options turned off in AziAudio.

This never happens building from New Audiocode 181 commit.  https://github.com/Azimer/AziAudio/commit/efc7c73ba4813f2b9f9ca6cf67b3d89502ab933a .

**Comment by Frank-74** [comment]
Removing this Sleep(1) from XAudio2SoundDriver.cpp fixes this issue.

https://github.com/Azimer/AziAudio/blob/master/AziAudio/XAudio2SoundDriver.cpp#L237

It also fixes VI's lagging and sound getting ahead.  Very noticeable in Body Harvest.
And fixes problem I had with musyx games needing a bigger buffer.

**Comment by theboy181** [comment]
release?

**Comment by Frank-74** [comment]
Here's my build with this Sleep(1) only turned on when Force Audio Sync is enabled, instead of removing it totally.  I also changed Backend and Buffer FPS to 95, slightly smaller buffer, but it's cleaner with Body Harvest.

Make sure Prevent Buffer Overruns is on, and Emulate Audio Interface is on, Force Audio Sync OFF.
FAT off for Body Harvest.

https://www.dropbox.com/s/9wv7nohyiz24mtf/AziAudioXA2.dll?dl=1

**Comment by Frank-74** [comment]
@theboy181
Try TWINE with FAT off and disable PJ64's framelimiter for good example of the audio staying clean at mega fast speed, and in time.

**Comment by theboy181** [comment]
Sounds pretty good.. Ill leave the plugin as default and report any issue I find. Do those settings need to be set every time? Is it the best settings for most games?

**Comment by Frank-74** [comment]
Leave Prevent Buffer Overruns and Emulate Audio Interface ON for every game.  Plugin remembers your settings.

There's still a problem with FAT off, in some games.  Goldeneye wants to run at 61-62 VI's, Super Smash Bros wants to run at 66 VI's.  I don't know if this is due to timing problem in PJ64 or if the plugin needs to use FAT timing method for correct audio timing.  Could remove FAT from PJ64 then.

**Comment by Azimer** [comment]
Hi Frank.  Have you tried Sleep(0) rather than Sleep(1) ?

The trouble not yielding a thread when there's nothing to do is it takes up CPU time that is unnecessary.  Alternatively, I can look into using messaging rather than sleeping.  We could also increase the number of audio frames sent to the device from 2 to 3 or 4 to cover a potential gap if the thread doesn't seize control in enough time.

I haven't gotten to your PR because March has been awfully busy for me.  I hope to change that this week but I need to investigate your issue further before removing thread yielding all together.

**Comment by Frank-74** [comment]
Just tried Sleep(0), there doesn't seem to be a noticeable difference between Sleep(0) and removing it.
I used the Force Old Audio Sync option to toggle it on/off.
		if (Configuration::getForceSync() == true)
		{
			Sleep(0);
		}

I just noticed RE2 takes a very long time to start if Prevent Buffer Overruns is on.  It starts immediately with it off.

**Comment by Azimer** [comment]
I wouldn't suspect there would be much difference in this place.  The amount of time to waiting needed may be less than timeslice.  I don't recommend ForceSync anyway...  it really isn't a good setting and should probably be removed.

However, I am mostly interested to see how it performs in XA2's thread.

**Comment by Azimer** [comment]
Frank - Can you give me a list of images you are having the most trouble with?  I'd like to toss them in my test.  So far I have Body Harvest.  Never heard of it.

**Comment by Frank-74** [comment]
I'll build the new master, and test a load of games this evening.  Though at the moment, with Sleep(0) and double size buffer, 95 FPS, all games are pretty good, some need PBO off with FAT off.  I have to do some shopping and cook Sunday roast first.

Body Harvest wasn't playable until a couple of weeks ago with GLideN64.  Body Harvest is same developers as Grand Theft Auto.  It was supposed to be included with the launch of the N64, but Nintendo boss wanted changes so was delayed for years.

**Comment by AmbientMalice** [comment]
Wouldn't the fact games keep trying to run at incorrect framerates be indicative of some timing issues on PJ64's side?

**Comment by Azimer** [comment]
HI @AmbientMalice, the FPS referred to here are audio FPS.  There's no hardware specifying how much framing is done.  Mario64, for example, frames their audio at ~60 fps to coincide with video FPS.  MusyX games seem to be at about ~120 fps.  Some games don't frame their audio at all.  These values really just say how the emulator itself will frame the audio.  For example, if we get a 4000 byte buffer from the emulated image and we have our frames set at 1000 bytes per frame, we end up reading from this buffer 4 times before triggering an interrupt.  This allows us to read from rdram and capture changes the game makes to the audio stream.  It causes problems in other areas which I have noticed a degradation in audio quality by not sampling on submitted frame sizes.

Clear as mud?

**Comment by AmbientMalice** [comment]
Makes sense.

**Comment by Frank-74** [comment]
@Azimer 
I sorted the Idle at 0.00% in Project64 with GLideN64/Body Harvest.  It was VSync setting.  Turned off VSync and Idle is ~50%.
However, with Sleep(1) here: https://github.com/Azimer/AziAudio/blob/master/AziAudio/XAudio2SoundDriver.cpp#L240, Idle goes back to 0.00%, and VI slowdown with audio getting ahead of video.  (And PJ64 Sync using audio with FAT slows every game to single digit VI's).  Sleep(0) here and Idle returns to ~50% and perfect sync again.

It must be either hardware or OS specific problem on my crappy Windows 8.1 laptop.  Because I get LESS CPU usage with Sleep(0).  The XA2Signalling experiment made it slightly worse.  The PBO Sleep(1) in Soundriver has no effect on CPU usage, it helps in most cases.

Can it just be an advanced option in the new configuration?

**Comment by Azimer** [comment]
Yes @Frank-74 .  I've expended enough time on the issue.  It will be a quick config option.  I hope to have the new configuration dialog ready within the next few days; including this change.

**Comment by Azimer** [comment]
Frank your changes to Sleep were implemented in this last patch.  Please reopen if this isn't the case.
