### ISSUE TITLE
dprintf()

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#187]
What is this `dprintf` thing for?

I am getting a lot of funny compile errors on lines inside my compiler's own `stdio.h`.

Took me a while to find out it's because AziAudio `#define`s a dprintf() on top of GCC's.

dprintf() according to Microsoft:
https://msdn.microsoft.com/en-us/library/windows/hardware/ff542750%28v=vs.85%29.aspx

dprintf() according to POSIX:
https://linux.die.net/man/3/dprintf

I think we really need to find a different name for this `dprintf` macro inside common.h.  MSVC's dprintf is different from others, causing inconsistencies and difficulty in keeping this plugin cross-platform while making references to that name.

**Comment by Azimer** [comment]
We'll get it fixed.  It's a very a useful debugging strategy for me to visually see when the audio plugin struggles.

**Comment by cxd4** [comment]
https://github.com/Azimer/AziAudio/commit/115f618553f50d3b9d241e9e4bbb9441d50188f4
