### ISSUE TITLE
DS8 restart crash with Realtek HD Audio

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#190]
I thought new drivers had fixed this.  But it's happening again, just not everytime.

I found a solution so it never crashes for me.  And also savestates still work.

```cpp
EXPORT void CALL RomOpen(void) 
{
	DEBUG_OUTPUT("Call: RomOpen()\n");
	if (snd == NULL)
		return;
	snd->AI_Startup();
}

EXPORT void CALL RomClosed(void) 
{
	DEBUG_OUTPUT("Call: RomClosed()\n");
	Dacrate = 0; // Forces a revisit to initialize audio
	if (snd == NULL)
		return;
	snd->AI_Shutdown();
}
```

I seem to have a problem with AI_ResetAudio in RomClosed.  Maybe it's because of slower hardware, don't know.

But this solution breaks switching plugins from XA2 to DS8.  Loses sound and stops responding.

**Comment by Frank-74** [comment]
This seems to work without crashes restarting DS8, losing sound switching plugins and loading savestates.

```cpp
EXPORT void CALL RomOpen(void) 
{
	DEBUG_OUTPUT("Call: RomOpen()\n");
	Dacrate = 0; // Forces a revisit to initialize audio
	if (snd == NULL)
		return;
	snd->AI_ResetAudio();
}

EXPORT void CALL RomClosed(void) 
{
	DEBUG_OUTPUT("Call: RomClosed()\n");
	Dacrate = 0; // Forces a revisit to initialize audio
	if (snd == NULL)
		return;
	snd->AI_Shutdown();
}
```

**Comment by Azimer** [comment]
I feel like I am going full circle.  The source you seem to be modifying seems old compared to https://github.com/Azimer/AziAudio/commit/1af1d07a75aac0dbc54080530f126d45f970060a.  This fixes #188 - the original request.

**Comment by Frank-74** [comment]
Sorry about that, yes it does lose audio changing plugins.

I'm getting the DS8 crashing again, until I restart windows, then it'll work until closing PJ64 and restarting PJ64 with the current source.  I've tried several things to get it to not crash.  The first breaks savestates, the second loses audio changing plugins, and as it is, DS8 crashes for me.

I guess it's just my Realtek and DSound.  As it's fine with Intel soundcard and Sigmatel C-Major onboard audio on an ancient 1Ghz laptop with XP.  I should change the title to include (with Realtek HD Audio).

**Comment by Azimer** [comment]
Tomorrow - I will check to see what all happens during Reset and make sure we aren't overly hitting the API with redundant requests to destroy and create objects.  This may alleviate your issues.

**Comment by Frank-74** [comment]
Thanks.

What I can't understand, it's fine before the new audiocode changes with ds8.  But nothing has changed with deinitialize.

Audio recording still sounds like shit on this laptop with the new drivers.  It's better on my 14 year old dell laptop, and a cheap Lynx10 tablet.

**Comment by Frank-74** [comment]
Still same crash with Yamaha Steinberg audio.

Found this in dxdiag log.
```
+++ WER1 +++:
Fault bucket 108785572440, type 1

Event Name: APPCRASH

Response: Not available

Cab Id: 0



Problem signature:

P1: Project64.exe

P2: 2.3.2.9999

P3: 589a665d

P4: AziAudioDS8.dll

P5: 0.0.0.0

P6: 58c3294d

P7: c0000005

P8: 0000a053

P9: 

P10: 
```

Here's details of device:
```
-------------
Sound Devices
-------------
            Description: Line (THR10)
 Default Sound Playback: Yes
 Default Voice Playback: Yes
            Hardware ID: USB\VID_0499&PID_1507&REV_0100
        Manufacturer ID: 1
             Product ID: 100
                   Type: WDM
            Driver Name: ysusb64.sys
         Driver Version: 1.09.0006.0001 (English)
      Driver Attributes: Final Retail
            WHQL Logo'd: No
          Date and Size: 10/13/2015 13:46:36, 144320 bytes
            Other Files: 
        Driver Provider: Yamaha Corporation.
         HW Accel Level: Basic
              Cap Flags: 0xF1F
    Min/Max Sample Rate: 100, 200000
Static/Strm HW Mix Bufs: 1, 0
 Static/Strm HW 3D Bufs: 0, 0
              HW Memory: 0
       Voice Management: No
 EAX(tm) 2.0 Listen/Src: No, No
   I3DL2(tm) Listen/Src: No, No
Sensaura(tm) ZoomFX(tm): No

---------------------
Sound Capture Devices
---------------------
            Description: Line (THR10)
  Default Sound Capture: Yes
  Default Voice Capture: No
            Driver Name: ysusb64.sys
         Driver Version: 1.09.0006.0001 (English)
      Driver Attributes: Final Retail
          Date and Size: 10/13/2015 13:46:36, 144320 bytes
              Cap Flags: 0x1
           Format Flags: 0xFFFFF
```

**Comment by Frank-74** [comment]
Think I've fixed it.  I've restarted Project64 several times, restarted with DS8 dozens of times.  No crash yet.

I just uncommented 	SampleRate = 0; // -- Disabled due to reset bug, in BOOL DirectSoundDriver::Initialize().

I'll do some more testing, but fingers crossed it seems to have fixed it.

**Comment by Azimer** [comment]
Can you publish your branch so I can compare changes?

**Comment by Frank-74** [comment]
https://github.com/Frank-74/AziAudio/tree/Fix-DS8-Crash

The only change is restoring the SampleRate=0 in Initialize.

**Comment by Frank-74** [comment]
Made new XA2/DS8 use config values for BitRate and SampleRate (24bit/48000).  Now musyx games don't stutter at all with bufferlevel at 2.  They're perfect.

https://github.com/Azimer/AziAudio/compare/master...Frank-74:config-bit-sample-rates

**Comment by Frank-74** [comment]
WOW!

Top Gear Rally is near PERFECT!  Music is perfect, sound effects is perfect.  I've just had a couple of crackles in the first minute, none since.

Strange thing is Alist is always 0.00%.

**Comment by Azimer** [comment]
Thanks for the branch Frank.  It sounds like making this configuration is the way to go.  I will move forward on it and investigate the SampleRate change.  If the change doesn't appear to cause any problems with plugin swapping or anything like that, I will make a commit to master.  If you want credit for the commit, feel free to make a PR, otherwise I will do some testing and push a commit later.

**Comment by Frank-74** [comment]
I'd rather you do some testing with the SampleRate = 0, which totally fixes crashing with DS8 for me.  But I don't know what it will do on other PC's.  My laptop appears to be very finicky.  Hence my reluctance to do a PR.

44100/16bit and bufferlevel 4 is what I settled on.

**Comment by Frank-74** [comment]
There is still a problem with F12/F11.  Which is an undocumented resume feature since the android changes.
F12 ends emulation, F11 resumes from a memory save.  New DS8/XA2 have no sound on F11 and lockup.  Legacy plugins don't lock up but have no sound.

Think this is because end emulation is destroying things it shouldn't.

**Comment by Azimer** [comment]
I think there are bigger issues that need to be investigated.  You fixed your crash (great) and I believe it's to do with SetLockSize...  however...  End Emulation/Start Emulation = No Sound.

**Comment by Frank-74** [comment]
>  End Emulation/Start Emulation = No Sound.

Only with F12/F11 or menu options.  Restarting from rom browser is fine.

**Comment by Frank-74** [comment]
Twisted Edge Snowboarding is perfect also...  :laughing:

**Comment by AmbientMalice** [comment]
@Frank-74 I notice WDC crashes on booth with this build. Interesting work, nonetheless.

**Comment by Frank-74** [comment]
@AmbientMalice Where does WDC crash?  I just tried both with default settings and never got a crash.  Tried HLE and LLE audio, Fat on and off.  No crash here.

**Comment by AmbientMalice** [comment]
@Frank-74 Sorry, my mistake. Video plugin was to blame.

**Comment by Azimer** [comment]
I plan on committing some changes tomorrow.  Weekends are usually not good for me to work on anything.

**Comment by Frank-74** [comment]
With the SampleRate=0 in Initialize, DS8 locks up PJ64 after a while.  Just start a game and leave it for 10 minutes or so.  Project64 will become unresponsive, menu no longer works.

**Comment by Azimer** [comment]
I don't believe this is an issue anymore?  I put SampleRate=0 back into Initialize and haven't seen an issue while testing.
