### ISSUE TITLE
plugin still says desinged for use with p64 2.1

### ISSUE THREAD

**Issue by budtz** [Azimer/AziAudio#194]
The plugin still says desinged for use with p64 2.1. Is this correct?

and will the disabled settings like select audio device be enabled someday? or maybe just removed?

**Comment by Azimer** [comment]
Hi @budtz welcome.  I am working on a new dialog now.  Being able to select an audio device and backend API implementation will be coming soon.  I changed the above to say "for use with Project64" without specifying a version.

Some other configuration settings are on the chopping block such as hot keys and logging.  Some additional options are being added.

**Comment by budtz** [comment]
Thx for the reply. Thats great. The text might confuse some users and make them think that the software is not optimal for their version.

**Comment by Azimer** [comment]
I removed the reference completely from the configuration dialog.  I will close the issue now.  Thanks!
