### ISSUE TITLE
Word Driver Championship and Stuntracer

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#2]
These games sound awful.  An on-demand option needs to be implemented, one that is compatible with other audio playback.

**Comment by cxd4** [comment]
Hm.  Has anyone else also been able to get either of these games booting with the latest AziAudio, or is it just me?  Need some more time but so far PJ64 just crashes with "Unknown memory action"; maybe it's the latest project64.exe I'm using or something.

**Comment by Azimer** [comment]
I'm pretty sure it worked with Project64 2.1.  I've never gotten an unknown memory action though so that is new to me if this is the case.  I should have a moment to sit down in the next couple days to retest unless someone else gets to it first.

**Comment by LegendOfDragoon** [comment]
For me it does not work in 2.1. XA2 WIP2 still works on PJ64 2.2, so I don't think it has anything to do with the emulator. The DS8 version works as well.

I first noticed this issue in XA2 WIP 4. As a reminder, i mentioned it here http://www.emutalk.net/threads/55161-Audio-v0-70-WIP-4-Feedback/page8

**Comment by Azimer** [comment]
Weird.  I will compile from the source and give it a try.  When I tested, I tested a release from last August.

**Comment by cxd4** [comment]
I can't very well remember @LegendOfDragoon, but weren't some of you commenting on an issue with the Project64 repository where RomOpen was having an issue because of something to do with something in Azimer's plugins?  Somebody ended up changing RomOpen with the core's handling of the audio spec at some point weeks ago, but I can't remember exactly when or what commit.  Might have to do some bunches of `git checkout` to narrow when this began exactly.

**Comment by LegendOfDragoon** [comment]
That was for loading save states. For some reason, XA2 WIP4 (and 5) crashes when loading save states on any emulator that uses RomClose during the loadstate process. I believe the deinitialization / initialization code needs to be looked at, in Azimer's XA2 code.

**Comment by cxd4** [comment]
It does boot if I turn on HLE gfx with Jabo's 1.7 plugin though.
Seems it's just that if I use LLE gfx plugins with WDC/SR64 then it crashes as I said.

**Comment by LegendOfDragoon** [comment]
>It does boot if I turn on HLE gfx with Jabo's 1.7 plugin though.
Seems it's just that if I use LLE gfx plugins with WDC/SR64 then it crashes as I said.

That's weird. Doesn't work for me at all.

Azimer should be able to easily fix this problem though. He just needs to fix initialization.

**Comment by cxd4** [comment]
Actually.  This time it worked in both versions, HLE || LLE graphics, without any failures.  Then I closed Project64.exe, then opened it again.  Now it fails to boot again with AziAudio.  Beginning to think this issue is pseudo-random.

>Azimer should be able to easily fix this problem though. He just needs to fix initialization.

orly?  what kind of initialization?  Something you know about that you could do a pull request to fix it?

**Comment by LegendOfDragoon** [comment]
I was hesitant because it might not be the way he'd want to do it, but I'll go ahead and make a PR anyway. Ended up finding a better way, so good thing I waited.

**Comment by Azimer** [comment]
WDC sends two buffers to the AI prior to starting the audio loop.  I don't believe this is being handled correctly in XA2.  It's not necessarily a problem with initialization on this game's part but definitely a problem with not emulating the AI correctly.  We'll get this sorted out before closing the issue.

**Comment by Azimer** [comment]
The stuttering should get fixed with the new audio code / FAT enabled.  Stunt Racer sounds better without FAT.  I still have a bunch of tweaking I need to do with BOSS games.

**Comment by Azimer** [comment]
Closing the issue.  Iterations will be made across WDC and Stuntracer continuously while testing changes.  I believe this will be a joint effort between Project64's FAT code and the plugin to get us to a point of good quality audio.
