### ISSUE TITLE
Clean up source and prepare to merge with Project64

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#201]
We need to clean up the source and get ready to merge the source into Project64's repository.

**Comment by oddMLan** [comment]
Have you seen Project64-Audio?

@Frank-74 can tell you more about that probably

**Comment by Frank-74** [comment]
Project64-Audio is a cut down version of the new audio code from DS8.

I just fixed getting rid of buffer settings.  Just have buffer level now.
After SystemType switch, I did this to get buffer size.
```cpp
		Frequency = (video_clock / (g_Dacrate + 1));
		audio_clock = ((video_clock / 32) + 1);
		buffer = audio_clock / (g_Dacrate + 1) + 0.5;
		if (Frequency < 8000) { return; }
        g_SoundDriver->AI_SetFrequency(Frequency, (uint32_t)buffer);

**Comment by Azimer** [comment]
Thanks @oddMLan .  I haven't been keeping up on Project64 since having to take a break for personal reasons.  I wasn't aware.  I might just abandon this project since it's no longer necessary (I have plenty of other plans).  I'll check out Project64-Audio... see what I think of it.

**Comment by cxd4** [comment]
I would imagine Project64-Audio actually is some fork of something from Mupen64Plus, like every other "Project64" plugin meant to get the emulator working on Android.  So it has to be more than just DS8 code.

**Comment by Frank-74** [comment]
Project64-Audio uses DS8 driver if win32, else OpenSLES.

**Comment by cxd4** [comment]
Which is funny because neither of those will work on non-Android & non-Windows systems.

Anyway, the point is that OpenSL ES is Android-only.  I'm sure that comes from M64P.

**Comment by Azimer** [comment]
I looked over the source.  Thanks @Frank-74 for the explanation above.  @cxd4 it is as you described but with DS8 code used if it's not android.  The OpenSL ES is indeed from M64P.
