### ISSUE TITLE
WIP builds?

### ISSUE THREAD

**Issue by SigmaVirus** [Azimer/AziAudio#213]
@Azimer, @cxd4 

Hi and thanks for all your efforts creating one of the best sound plugins for N64 emulation!

Would it be possible to acquire a test/WIP build for the latest commits? I have a build from 17-10-09 and it's one of the later WIP 7 builds.

Much have happened since then and the plugin version seems to be at WIP 9 now with a lot of neat changes. 

Thanks in advance!

**Comment by cxd4** [comment]
Yes, by running one of the Windows build scripts for MSVC or MinGW.

**Comment by Azimer** [comment]
I created a release tag for WIP9 and zipped a binary for 32bit.  https://github.com/Azimer/AziAudio/releases/tag/v0.70-WIP_9

**Comment by SigmaVirus** [comment]
@Azimer 

Thank you very much, the plugin worked perfectly!

@cxd4 

I know you meant well, but what you said doesn't mean much to a layman like me.
I have been relying on EmuCR builds in the past for my AziAudio needs but they have been pretty stagnant lately so that's why I turned to here.

But I love your RSP so much cxd4 and it's AAA Excellent!

**Comment by Azimer** [comment]
Good.  I am going to close this Issue then since we've made a release on github with the latest changes.  Look forward to 0.70 Final (non-WIP) coming soon.

**Comment by SigmaVirus** [comment]
@Azimer 

Thanks for closing the issue and thanks for the updated plugin again!

I'm really looking forward to the final result and with this WIP I think I know how excellent it will be as I didn't hear anything out of the ordinary, anything weird or any form of sound distortions at all.

However I don't own all N64 games though, just 12 but they sounded perfect compared to the earlier WIP build.
