### ISSUE TITLE
Rework code to compile as a 64bit DLL

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#22]
Some low priority work, but we should ensure the DLL will compile as a 64bit binary with no explicit pointer type casts (ie iLong = (unsigned int)(char *)variable)

**Comment by cxd4** [comment]
I am pretty sure I should be able to tackle that one.  zilmar was talking a little about the possibility of having a 64-bit Project64, and it really would be nice if we could start having 64-bit plugins.  I would like to give him only more reason to think it's feasible by porting this plugin to 64-bit.

I have only two minor issues:
1.  I haven't yet found a way to install Mupen64Plus 1.5, which is the only 64-bit N64 emulator which still supports zilmar's spec.
2.  How should the VS solution file be updated?  Should I just copy the Win32 settings to the x64 settings to whatever works to get a 64-bit binary going, or should I leave that alone and let you set how the solution file should be when there is a 64-bit target?

**Comment by Azimer** [comment]
Yeah.  I'd go ahead and copy Win32 and retarget it for x64 plus whatever changes are required to make it work.  We won't have a way to test it yet but if we can get it to compile as 64 and 32 bit and the 32bit still works, we can test the 64bit when it's able to be tested.

**Comment by LegendOfDragoon** [comment]
@Azimer , this guy forked your old audio plugin a while back.
https://github.com/r52/azimer0551

Pretty sure it compiles in 64 bit too, because he's working on a 64 bit emulator.

**Comment by cxd4** [comment]
I seem to have mostly "fixed" this issue except that the Release mode of VS config is claiming I'm linking something x86 against x64.  I put up a pull request to where I left off, but the Debug mode does build a 64-bit plugin with only 2 level-3 warnings.

**Comment by Azimer** [comment]
Thanks @cxd4.  I will take a look at it and see if I can do anything with it after it's been merged.  @LegendOfDragoon, thanks for the link.  It might prove to be useful in the future if I need to refer back at something.

**Comment by Azimer** [comment]
My latest commit fixes the issue you were having @cxd4 8a104c02765e2291e4ea6a4a4a31f8285b7e7931 .  The folders were still x86 not x64.

**Comment by cxd4** [comment]
That explains it.

I would have never noticed probably, as I pretty much just go through the VS IDE for all settings.  I'm not confident in editing the solution/project files in a tex editor.

**Comment by Azimer** [comment]
I think the base work is completed and 64bit binaries compile.  I am going to close the issue unless there happens to be more than needs to be done.
