### ISSUE TITLE
Emulate Audio Interface and Project 64.

### ISSUE THREAD

**Issue by AmbientMalice** [Azimer/AziAudio#23]
I was wondering how this setting functions with PJ64, especially with PJ64 FAT and AI=0. Does it conflict? Or is it harmless?

**Comment by Azimer** [comment]
It's harmless and preferred to be used with PJ64 FAT.  Essentially it turns the plugin into a streaming audio player and doesn't even attempt to trigger interrupts or return back status or length.

**Comment by Azimer** [comment]
Can this issue be closed?
