### ISSUE TITLE
ABI HLE restructuring

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#24]
I am thinking we'll want to separate out the commands from ABI1-ABI3.cpp into seperate command files envmixer.cpp, mixer.cpp, adpcm.cpp so it's easier to take out what's in common.  ABI1-ABI3.cpp should strictly be for defining the commands awhile the command source files contain the commands for all 3 implementations.  It will have smaller source files and less change of collisions in a collaborative environment.  It will allow us to take out what's in common between all three "ABI"s and allow reuse among them.  I also believe it will be more readable / maintainable.

**Comment by cxd4** [comment]
I agree against defining the functions common to ABI1/2/3 within ABI1/2/3 themselves, though I didn't think about the possibility of having new .cpp files like mixer.cpp, adpcm.cpp etc.  So far I just put the pack_signed and RSP clamping stuff in the central `HLEMain.cpp`, though I guess only so much can go in there until it becomes more than about, well, "HLE main". :P

So I liked this commit:
https://github.com/samuelyuan/AziAudio/commit/354ddd2ca12a59b87d0546bc4bac602904b60eca

But as said, better to either make a new .c file out of it or have it in HLEmain.  The only reason I wouldn't want to make a new .c file out of these common ABI functions is just if the only thing in them is that single function--if there are multiple ADPCM-related functions for example I would much rather have all that stuff in a new file adpcm.cpp.  But if it boils down to a single small function with just a loop in it like samuelyuan's commit above, eh idk, seemed like it could have gone maybe in HLEMain.

**Comment by Azimer** [comment]
Agreed with not having just a few files containing minor functions.  There could easily be a single catch-all for those.  I will make a branch and present my idea at some point.

**Comment by Azimer** [comment]
Proposing a change in PR https://github.com/Azimer/AziAudio/pull/26.

**Comment by cxd4** [comment]
Hah.  I am glad I waited for you to do it instead of me.  That is a lot of cleaning up the common stuff to their own sources.

Even looks like you made the most of the new modules--better documents the same basic kind of things the different ucodes will do.  I think it looks great.

**Comment by samuelyuan** [comment]
Looks nice. It definitely makes it much easier to refactor code with similar looking code right next to each other. 

I'll wait until the pull request is merged before making changes.

**Comment by Azimer** [comment]
More changes are occurring but I am going to close this base issue since the task was completed in #26 and nothing as drastic needs to be completed going forward.
