### ISSUE TITLE
Compiling with VS2008

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#29]
I found an open source stdint.h for Visual Studio here : https://code.google.com/p/msinttypes/
Replaced stdbool.h with a typedef:
```
typedef int bool;
#define true 1
#define false 0
```
But get these link errors and am now lost.
```
   Creating library AziAudio.lib and object AziAudio.exp
ABI2.obj : error LNK2019: unresolved external symbol __imp__MessageBoxA@16 referenced in function "void __cdecl SPNOOP(void)" (?SPNOOP@@YAXXZ)
ABI3.obj : error LNK2001: unresolved external symbol __imp__MessageBoxA@16
HLEMain.obj : error LNK2001: unresolved external symbol __imp__MessageBoxA@16
main.obj : error LNK2001: unresolved external symbol __imp__MessageBoxA@16
main.obj : error LNK2019: unresolved external symbol __imp__IsDlgButtonChecked@8 referenced in function "int __stdcall ConfigProc(struct HWND__ *,unsigned int,unsigned int,long)" (?ConfigProc@@YGHPAUHWND__@@IIJ@Z)
main.obj : error LNK2019: unresolved external symbol __imp__EndDialog@8 referenced in function "int __stdcall ConfigProc(struct HWND__ *,unsigned int,unsigned int,long)" (?ConfigProc@@YGHPAUHWND__@@IIJ@Z)
main.obj : error LNK2019: unresolved external symbol __imp__SendMessageA@16 referenced in function "int __stdcall ConfigProc(struct HWND__ *,unsigned int,unsigned int,long)" (?ConfigProc@@YGHPAUHWND__@@IIJ@Z)
main.obj : error LNK2019: unresolved external symbol __imp__GetDlgItem@8 referenced in function "int __stdcall ConfigProc(struct HWND__ *,unsigned int,unsigned int,long)" (?ConfigProc@@YGHPAUHWND__@@IIJ@Z)
main.obj : error LNK2019: unresolved external symbol __imp__DialogBoxParamA@20 referenced in function _DllConfig
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__CoInitializeEx@8 referenced in function "public: __thiscall XAudio2SoundDriver::XAudio2SoundDriver(void)" (??0XAudio2SoundDriver@@QAE@XZ)
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__CoUninitialize@0 referenced in function "public: virtual __thiscall XAudio2SoundDriver::~XAudio2SoundDriver(void)" (??1XAudio2SoundDriver@@UAE@XZ)
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__CoCreateInstance@20 referenced in function "long __cdecl XAudio2Create(struct IXAudio2 * *,unsigned int,enum XAUDIO2_WINDOWS_PROCESSOR_SPECIFIER)" (?XAudio2Create@@YAJPAPAUIXAudio2@@IW4XAUDIO2_WINDOWS_PROCESSOR_SPECIFIER@@@Z)
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__WaitMessage@0 referenced in function "public: virtual void __thiscall XAudio2SoundDriver::AiUpdate(int)" (?AiUpdate@XAudio2SoundDriver@@UAEXH@Z)
AziAudio.dll : fatal error LNK1120: 10 unresolved externals
```

**Comment by cxd4** [comment]
Not sure but possibly, with VS2008 you might have to specify to add `user32.lib` and `comctl32.lib` on the project settings :: Linker :: Input?  Because those are the link-time libraries where those references are found in, and that looks like it's not automatically specifying them on its own.

**Comment by cxd4** [comment]
About the stdint.h, do whatever gets the job done for that, but I've already made my own `my_types.h` from my cross-platform, 64-bit-compatible attempt of zilmar's plugin spec headers.
https://github.com/cxd4/rcp64/blob/master/my_types.h

The long and short of it is that with this header of mine I should be able to type either the uint32_t or u32 style of type names (though I much prefer the later myself) without conflicts or requirements of a pre-existing stdint.h.  But my VS2008 Professional Edition trial from building pj64 expired so I can't make the solution for that myself.

**Comment by Frank-74** [comment]
Adding user32.lib and comctl32.lib fixed all but these in Xaudio2.  I have no xaudio2.lib in DX SDK.
```
   Creating library AziAudio.lib and object AziAudio.exp
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__CoInitializeEx@8 referenced in function "public: __thiscall XAudio2SoundDriver::XAudio2SoundDriver(void)" (??0XAudio2SoundDriver@@QAE@XZ)
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__CoUninitialize@0 referenced in function "public: virtual __thiscall XAudio2SoundDriver::~XAudio2SoundDriver(void)" (??1XAudio2SoundDriver@@UAE@XZ)
XAudio2SoundDriver.obj : error LNK2019: unresolved external symbol __imp__CoCreateInstance@20 referenced in function "long __cdecl XAudio2Create(struct IXAudio2 * *,unsigned int,enum XAUDIO2_WINDOWS_PROCESSOR_SPECIFIER)" (?XAudio2Create@@YAJPAPAUIXAudio2@@IW4XAUDIO2_WINDOWS_PROCESSOR_SPECIFIER@@@Z)
AziAudio.dll : fatal error LNK1120: 3 unresolved externals
```

**Comment by Azimer** [comment]
Make sure you are including OLE32.lib.  There is no xaudio2.lib for 2.7 because it uses COM.

**Comment by Frank-74** [comment]
Thanks, I'll try that later.  I just managed to build the DX version by commenting out the #ifdef USE_XAUDIO2 conditions.  And it works fine in Project64.  Larger AziAudio.dll though at 141Kb, but I haven't applied any optimizations.

So it will build with VS2008 and the DX SDK.

**Comment by cxd4** [comment]
Yeah, could #undef USE_XAUDIO2, though I think it's safer to #define XAUDIO_LIBRARIES_UNAVAILBLE in the project C pre-processor settings.

**Comment by Frank-74** [comment]
Compiled the current master using codeblocks with VS2008.  Added libraries dsound.lib, user32.lib, comctl32.lib and ole32.lib.
Had to add #include <stdint.h> to arithmetics.h.  Remove #include <stdbool.h> from musyx.c, and replace with `typedef int bool;
#define true 1
#define false 0`
Also restore afxres.h to resource.rc.

It now builds both DX and XAUDIO versions.  And one thing very noticeable to me is XAUDIO2 version is low quality sound compared to the DX version.  Thin sounding, a bit like how Top Gear Rally sounds but not as worse.  Its noticeable starting GoldenEye.

**Comment by cxd4** [comment]
> Had to add #include <stdint.h> to arithmetics.h, and use https://code.google.com/p/msinttypes/ headers.

I forgot, bsmiles uses a intfast16_t or w/e type, instead of just int16_t.  You could easily replace that though without including `<stdint.h>`, and it would break nothing.  I would tend to avoid making people have to install that header if their specific compiler did not choose one already.

>Also restore afxres.h to resource.rc.

Why was that needed?  We still have Project64 compiling in VS2008 without afxres.h, so why start needing that header now?

**Comment by Frank-74** [comment]
> Why was that needed? We still have Project64 compiling in VS2008 without afxres.h, so why start needing that header now?

Because, I was getting link conflicts with msvcrt.lib and assert.

**Comment by LegendOfDragoon** [comment]
>It now builds both DX8 and XA2 versions. One thing very noticeable to me is XA2 version is low quality sound compared to the DX8 version. Thin sounding, a bit like how Top Gear Rally sounds but not as worse. Its noticeable starting GoldenEye.

@Frank-74 is this a possible regression? I ask because I've encountered a strange problem recently. Haven't tracked down the cause and not sure if I broke something on my end or if there's a regression. I know that some games happen to sound better on the DS8 version, due to differences in AI emulation, but many sound better on the XA2 version (due to the way it handles AI emulation).

**Comment by Frank-74** [comment]
@LegendOfDragoon  I've just recorded the start of GoldenEye with XA2 and DS8 versions for comparison.  Its very noticeable when the music starts.

https://dl.dropboxusercontent.com/u/9498358/n64/ge_DS8.mp3
https://dl.dropboxusercontent.com/u/9498358/n64/ge_XA2.mp3

**Comment by cxd4** [comment]
Reminds me of something zilmar said about having no sound in his 2008 build of it.

I think I need to get on my VS2008 Express laptop to try to set up the working solution and get it to compile there.  I want to try to make this as easy as possible for everyone.  Really I would have thought that if changing compilers would create bugs, then just building it on MinGW would create bugs.  Then again I still do have yet to get the MinGW build compiling with XAudio....

**Comment by cxd4** [comment]
This compiles in VS2008 now as per the changes I made here, correct?https://github.com/Azimer/AziAudio/pull/47

Or otherwise is this issue left open as a reminder of anything else remaining?

**Comment by Frank-74** [comment]
I can't open the VS2008 Express sln with VS2008 Professional.  Says unrecognised version.  I'll see if I can fix it later, have to go to band practice.  Its probably something to do with property sheets or something.   I remember I could open VS2008 Professional solutions with VS2008 Expresss, it just warned me about property sheets.

**Comment by cxd4** [comment]
Interesting.  I know I was able to open a Express solution with Professional on another project I was working on, but I do a lot of careless changes caused by the VS IDE and don't carefully check the low-level changes in the project text files themselves very much.

I was sort of intending on merging more of zilmar's differences in his own VS2008 solution file he got working over the one I did (wanted to do my own first to experiment) anyway, so yeah do whatever's necessary there.

**Comment by Frank-74** [comment]
Just got home from band practice, gonna have a cup of tea and then look at seeing if I can edit the Express sln to work in professional.  I myself never got it to build using MS VS2008 Professional IDE.  But I was succesful with both DS8 and XA2 version using CodeBlocks with VS2008 compiler.  The only difference being dll's were about 170Kb.

**Comment by cxd4** [comment]
Might have been 170 KB from not passing -s to the linker or doing --strip-all; I think that was about the size I had before I added some flags to strip the standard library debugging symbols, optimize a few modules for size not speed etc..

**Comment by Frank-74** [comment]
It was a simple change in the sln to open it.

`# Visual C++ Express 2008` to `# Visual Studio 2008`.

I also converted from U8-UNIX to DOS format to match zilmar's.  Does it still open with `# Visual Studio 2008` in Express?

**Comment by cxd4** [comment]
I edited the `# Visual C++ Express 2008` to replace it with `# Visual Studio 2008` using Microsoft Notepad to save changes, and yeah it looks like VS 2008 Express still loads the solution and builds the plugin and all.

I don't mind ditching the "C++" part anyway since it's a reference to something that sucks, so I prefer "Visual Studio 2008".

**Comment by Frank-74** [comment]
It builds here too.  So I guess this issue can be closed with that change.  Doesn't matter what format the file is saved in, just tried without changing to DOS and its the same.
