### ISSUE TITLE
XA2 sounds lower bit rate compared to DS8.

### ISSUE THREAD

**Issue by Frank-74** [Azimer/AziAudio#38]
I've recorded the start of GoldenEye with XA2 and DS8 versions for comparison.  Its very noticeable when the music starts.  XA2 sounds like a lower bit rate.  Like comparing scratchy vinyl against tape/cd.

https://dl.dropboxusercontent.com/u/9498358/n64/ge_DS8.mp3
https://dl.dropboxusercontent.com/u/9498358/n64/ge_XA2.mp3

HLE Audio unchecked in PJ64 plugin options.

**Comment by LegendOfDragoon** [comment]
Are you using FAT?

**Comment by Frank-74** [comment]
Yes FAT with AI=0, sync using audio off.  I'm testing every game with those settings at the moment.

**Comment by LegendOfDragoon** [comment]
I honestly can't tell a significant difference between the 2 audio files you linked. I wonder if I'm losing my hearing :( .

**Comment by cxd4** [comment]
wat

**Comment by theboy181** [comment]
HE SAID HES WONDERING IF HE IS LOOSING HIS HEARING!

**Comment by cxd4** [comment]
WAT!

**Comment by theboy181** [comment]
![capture](https://cloud.githubusercontent.com/assets/9299743/7487038/52ad16ec-f364-11e4-9a7c-4934119c9044.PNG)

**Comment by cxd4** [comment]
O!  y u no say sew11212

I just clicked both of those, and they sound the same to me.  Maybe the XA2.mp3 was originally a lower waveform frequency, but when Frank uploaded it or when I play it directly through FireFox it's projecting it at an automatically converted frequency to make it sound normal compared to how he uploaded it.

**Comment by Frank-74** [comment]
Play them in a proper player,something like winamp or vlc.  Just not Windows Media Player, as that plays back in bad quality anyway.  I just tried them in firefox, they still sound very different tone to me.  XA2 is tinny, drum hi hat and snare is wishy shishy sounding.  DS8 is fuller, snare has more pow, and hi hat has a tish not shish tone.

**Comment by Frank-74** [comment]
I think I found the problem in XAudio2SoundDriver.cpp.
```
	wfm.nSamplesPerSec = 32000;
	wfm.wBitsPerSample = 16; // TODO: Allow 8bit audio...
```
Whereas in DirectSoundDriver.cpp;
```
	wfm.nSamplesPerSec = 44100;
	wfm.wBitsPerSample = 16;
```

**Comment by AmbientMalice** [comment]
3200HZ MASTER RACE.

**Comment by Frank-74** [comment]
Nope, changing that to 44100 alters nothing...

**Comment by Frank-74** [comment]
Think its problem in `void XAudio2SoundDriver::SetFrequency(DWORD Frequency)`

**Comment by Frank-74** [comment]
Got it I think, needs more work, but basically the XAudio is using DirectShow, WAVEFORMATEX, where it probably should be using XAUDIO2_VOICE_DETAILS.  https://msdn.microsoft.com/en-us/library/windows/desktop/microsoft.directx_sdk.xaudio2.xaudio2_voice_details%28v=vs.85%29.aspx

**Comment by oddMLan** [comment]
XAudio sounds much higher quality to me than the DS8 version.

**Comment by LegendOfDragoon** [comment]
After seeing other people say they couldn't hear a difference, I feel relieved :) . I'm usually able to pick up on audio issues pretty fast. That's why I don't say things like "this audio plugin / emulator has perfect sound".

On my end I cannot really tell a difference between the 2, when FAT is enabled. If there is indeed a significant difference, it must be related to hardware / OS.

**Comment by Frank-74** [comment]
I have a degree in sound engineering, a doctorate in music, have worked in sound engineering/recording/performing for 20+years.  And I am 100% positive that XAudio is shitty quality compared to DS8.  Frequencies of samples are lost in unnecessary sample rate conversions.  Making the output lose midrange and detail in high frequency.

There is sample rate conversion going on that is deteriorating the output of the samples as they should be heard.  Provable by altering the mastering output sample rate to a lower level, which should lower the quality of output but it doesn't, because of unnecessary sample rate conversion the XAudio is doing on every different sample to the master output.  Using submix voices would lower CPU usage and increase fidelity.

XAudio cannot playback different sample rates to the output like DS can.  If the input/ouput sample rate doesn't match what is set, there is sample rate conversion.  Hit on the CPU and degradation in quality.

**Comment by LegendOfDragoon** [comment]
I should have mentioned that I'm using cheap ear phones (although I'd say they are good quality for the price I got it for). So I don't totally doubt what you're saying @Frank-74. I know that using better audio equipment makes a huge difference. You have Windows XP, so I was thinking maybe part of the issue has to do with that.

In any case, I actually like DS8. Seems to be good enough for N64 emulation anyway.

**Comment by Frank-74** [comment]
I have 8.1 on a laptop as well.  Same results here when using the same stereo amplifier for sound output.  A Mackie 1200 watt PA, PC outputs to channels 1 and 2 on a Mackie Onyx 24.4 desk going into the PA.  My PC is in my music studio.

**Comment by Azimer** [comment]
Frank, if you can code any improvements (or adding ASIO), I am happy to add them.

XAudio2 does not run natively on WindowsXP, it uses DirectSound.  So if you are indeed using WindowsXP, that could be the reason you are hearing a difference.  I do 90% of my programming currently on Windows 8 the rest on Windows 7.  If XAudio2 is giving XP users trouble, that is an important point and something that needs to be considered.

**Comment by Frank-74** [comment]
@Azimer I've always wanted to add ASIO, have been getting to know whats needed for the API in the source over the past couple of days.  I've only ever written a simple mic input sample recorder using ASIO before, so I'm treading in unknown ground.  Starting by just translating what you've done already.  Mac users would love ASIO as its the original native API for Mac.

**Comment by Azimer** [comment]
I've never looked at ASIO but I have a partial WSAPI implementation.  Being Mac friendly would be nice.

**Comment by cxd4** [comment]
You guys just have decent headphones.  Mine are falling apart. :3

**Comment by cxd4** [comment]
http://wiki.audacityteam.org/wiki/ASIO_Audio_Interface

>The ASIO technology was developed by German company Steinberg and is protected by a licensing agreement which prevents redistribution of its source code.  Audacity, as an open source program licensed under the GPL, is therefore currently unable to support ASIO, despite being ASIO-capable (providing the user's sound device is similarly capable). If ASIO support were distributed in Audacity builds this would either violate Steinberg's licence agreement if the code were included, or conversely would violate Audacity's GPL Licence if the code were withheld.

lol nut

**Comment by Frank-74** [comment]
This seems to fix XA2 sound.
```
void XAudio2SoundDriver::SetFrequency(DWORD Frequency)
{
//	Frequency = (Frequency+25) - ((Frequency+25) % 50);
	if (Frequency < 45000 && Frequency > 43000)
		{
		Frequency = 44100;
		}
	else if (Frequency < 33000 && Frequency > 31000)
		{
		Frequency = 32000;
		}
	else if (Frequency < 25000 && Frequency > 20000)
		{
		Frequency = 22050;
		}
	else if (Frequency < 15000 && Frequency > 10000)
		{
		Frequency = 11025;
		}
```

**Comment by LegendOfDragoon** [comment]
@Frank-74 in Goldeneye, the Frequency turns out to be 22050 regardless. So if anything the difference was simply wfm.nSamplesPerSec = 44100;

**Comment by Frank-74** [comment]
The drums in particular play with a lower key, which changes the sample rate they're played at.  Putting back that switch case makes XA2 sound much better.  True, Goldeneye may not go above 22050, but it goes below.  I set wfm.nSamplesPerSec to 44100 because its the highest available in that switch.

No, not using PAL.  There is another problem with goldeneye in PAL, and that is the key is transposed to a higher pitch.  A semitone or two higher.  Same with all audio plugins.

**Comment by Frank-74** [comment]
An ideal solution would be to use an interval calculation.  The frequency ratio of the interval between two adjacent notes, is the twelfth root of two.

**Comment by LegendOfDragoon** [comment]
@Frank-74 , I played Goldeneye for a few minutes and haven't seen the frequency change. I think rounding to nearest 50 is better.

**Comment by Frank-74** [comment]
With audio, seeing is not believing, hearing is believing.  Use your ears.  If the input (sourcevoice) sample rate isn't a division of the output (mastervoice) sample rate, the samples will sound degraded.  Only submix voices can have a different input sample rate to the mastervoice output using SRC.

**Comment by cxd4** [comment]
>I think rounding to nearest 50 is better.

I was always doing this myself in audio plugins but I see that Azimer is accounting for a frequency of 11,025 Hz?  I wonder what game does that.  If I had known that I would not be rounding to the nearest 50.

**Comment by LegendOfDragoon** [comment]
>With audio, seeing is not believing, hearing is believing. Use your ears. If the input (sourcevoice) sample rate isn't a division of the output (mastervoice) sample rate, the samples will sound degraded. Only submix voices can have a different input sample rate to the mastervoice output using SRC.

I don't think depending on hearing is reliable enough. When i said, I didn't see a change in frequency, I actually ran Goldeneye through a debugger and it only called SetFrequency once and is 22050 regardless of which of the 2 algorithms used. So I was saying that code will not make a difference in Goldeneye, unless perhaps some random part of the game has a frequency change (certainly not the intro or beginning of 1st level).

>I was always doing this myself in audio plugins but I see that Azimer is accounting for a frequency of 11,025 Hz? I wonder what game does that. If I had known that I would not be rounding to the nearest 50.

I actually got the idea from you :smile: . When I round to the nearest 50, games like WDC = 22000 for the sample rate. Would 22050 really be better? I'm not sure if any game uses around 11025 Hz. Lowest I've seen was 16000 Hz after rounding to nearest 50.

**Comment by cxd4** [comment]
22050 is standard.  You might have known, it's half of 44100.

**Comment by LegendOfDragoon** [comment]
>22050 is standard. You might have known, it's half of 44100.

I'm aware. Just seems weird to me how some games are closer to 22050 while others are closer to 22000 ;/ .

**Comment by cxd4** [comment]
Mario Kart has a weird freq. too if you look, forget exactly, 20k something.

**Comment by LegendOfDragoon** [comment]
You're right @cxd4. 26807 for Mario Kart. Polaris SnoCross uses 22496. VRally uses 21617.

**Comment by theboy181** [comment]
Frank hearing is believing can you drop box your DLL so I can have a listen?
