### ISSUE TITLE
Donkey Kong 64 rap not synced

### ISSUE THREAD

**Issue by theboy181** [Azimer/AziAudio#44]
Audio in DK64 is not synced.

On the real HW the last word in rap is SHELLS. This is cut off when playback is set using FAT=0. This currently ends with COCONUT as the last word.   

So close!!

**Comment by cxd4** [comment]
CPU-RCP synchronization happens outside the plugins.  Actually DK64 is even worse outside pj64.

**Comment by LegendOfDragoon** [comment]
Considering you're using FAT, I don't see why you opened the issue here.

**Comment by theboy181** [comment]
Please explain further, I don't understand.

I tested this two builds ago and it wasn't even close to being sync with AzimerAudio. PJ64 recently change?

**Comment by LegendOfDragoon** [comment]
When using FAT, the timing is done in the core..

@theboy181 feel free to look at commit history. Whatever the problem you had before, is likely a problem on your end because people gave good feedback soon after Azimer submitted his PR to PJ64 for FAT.

**Comment by Frank-74** [comment]
@theboy181 See if you can find a value for the VI that syncs the end of the rap with shells.  My current build with a slight timing adjustment with no rounding of frequencies, gets to 'SHE' of 'COCONUT SHELLS'.  So its a little better but still not absolutely perfect.

Another way of adjusting the timing is to alter the NTSC video clock frequency slightly.  Its a finer, more precise adjustment.

**Comment by theboy181** [comment]
Would adjusting the clock rate only prove that they are set incorrectly in the first place ?

**Comment by Frank-74** [comment]
What is correct?

If you were to line up a 100 REAL N64's, and measure the clock rate of each one, I guarantee you that you wouldn't find two the same.

What's most important is that both the VI and AI are in sync.

**Comment by AmbientMalice** [comment]
With PJ64, Counter Factor was set to 1 to reduce tearing. This isn't actually needed anymore, since FAT+AI=0+Azimer's seems to have no tearing.

CF2 is a smidge closer to accurate, cutting off halfway through "shells". But TBH, I think that getting it perfect will prove painfully tricky. Perhaps even impossible without some cycle accurate timing.

Currently, PJ64 is set to enable Jabo's Audio Sync by default, which provides *reasonably* close sync with Jabo's plugin, but with some polygon tearing.

**Comment by Frank-74** [comment]
I've just managed to get this in sync.  Default settings and plugins in PJ64.
Disable Sync using audio and FAT=534.

**Comment by AmbientMalice** [comment]
@Frank-74 Not bad, not bad at all.

**Comment by theboy181** [comment]
You did it great job!!
Now lets see if these settings continue ot work while the plugin goes through changes.. :)

**Comment by cxd4** [comment]
wasn't about the plugin.

**Comment by theboy181** [comment]
are you sating that ll audio audio plugs will be OK with these settings then?

**Comment by Azimer** [comment]
@Frank-74 : What are your VI settings set to?  I'd like to see what FAT=0 is setting the game at as opposed to what you are doing.

**Comment by oddMLan** [comment]
>I've just managed to get this in sync. Default settings and plugins in PJ64.
Disable Sync using audio and FAT=534.

AMAZING! The intro is **perfectly** in sync now using Azimer's XA LLE (HLE is slightly offsync for some reason). Crystal clear audio, no video stuttering and absolutely no audio crackling or popping. Wow guys, seems like we're getting closer to the N64 emulation everyone dreamed years ago.

**Comment by LegendOfDragoon** [comment]
@oddMLan, it's not consistent.

**Comment by oddMLan** [comment]
Hmmm... you're right. If you soft reset the game the rap if out of sync again. Although using Angrylion's RDP makes the result from test to test more consistent. Also one thing to consider too is that PJ64 does not emulate the real N64 slowdowns.

Still, that's much closer than what we had before. By the way, how did you calculate that value @Frank-74 ? By trial and error or by some number calculated based on a certain parameter (like the DAC rate)?

**Comment by LegendOfDragoon** [comment]
Based on the calculation for FAT, while using VI refresh of 1500, the AI counter per byte for DK64 is 536 iirc, since its Sample Rate = 22047. The ideal number should naturally be close to the calculated value. Are you guys sure 534 is better than 536/0?

**Comment by Azimer** [comment]
This is the same result I get on the real N64.  It doesn't end at coconut shells.  It ends in the middle of walnuts.  https://youtu.be/npuuTBlEb1U?t=195 .  I tried it 5 times on the real console and it ends in the same place every time.  I don't believe at this very point in time we will be in perfect sync without trying to gain more accurate timing.

**Comment by cxd4** [comment]
I forgot that's right, it's been years but it never ended in "coconut shells", always ended in the beginning of "walnuts" for me when I used to play it

lol bunch of pirates, lrn2realhardware before celebrate emulation

**Comment by theboy181** [comment]
You going be memory?  I tested on the real HW. You opinion doesn't hold up to my rocking N64 from the 90's.

**Comment by cxd4** [comment]
> I tested on the real HW.

Well actually I had tested on the real hardware and you're going by memory and your opinion doesn't hold up to the fact that I'm right which means this argument is pointless until you test it on real hw. :D

**Comment by oddMLan** [comment]
Maybe the NTSC and PAL version of the game have slightly different timing on the rap. I heard the developers had to make the the Kong's walk cycle faster on the PAL version to compensate the lower frame rate.

**Comment by cxd4** [comment]
Quite possibly.  I think after 2000 I got the physical cartridge and did not know how to check back then, though I would be surprised if it was the PAL version so imagine it was NTSC.  And history tends to lead me to the hallucination that I have a very saturated memory skill for tons of these trivial little flashbacks, which includes the rap ending at the early termination of the next "Walnuts" when I played it.

If it ended at coconuts instead that was while I was playing it on pj64 1.6 instead.

**Comment by Frank-74** [comment]
I set the AI to end in the middle of WALNUTS, so it finishes at exactly the correct time as on real N64, and the video/audio go out of sync (samples start too early).  The samples are always playing too long.  Maybe its rounding the GetLength values up and aligning to 4 bytes (16 bit stereo sample size), that is making the samples too long.  Need to round down by more than a few samples instead maybe, as 1 is not enough.

**Comment by oddMLan** [comment]
I think there's no possible way to get this in sync with the N64 without handling more accurate timing in the core emu, including emulating the real N64 slowdowns.

534 is the closest value that gets the rap in sync using LLE Audio + HLE graphics (PJ64Glide)
Maybe 536 (the value that gets automatically calculated when AI is set to 0) is the _real_ value but because we're not emulating the N64 slowdows, it doesnt look in sync. Compare the rap from a real N64, is not as smooth as the emu.

Maybe related too but the loading times in PJ64 2.2 are faster than the real console, which brought CosmoSpeedRuns to ban PJ2.X from speedruns (PJ64 1.6 is apparently OK).

**Comment by Frank-74** [comment]
Raising the VI Refresh Rate I can get it ending on OH YEAH.  VI=3000, AI=1066, Counter Factor=2.
If I hear that rap one more time I'll probably develop a mental illness.  So this is it until the timing gains more accuracy.

**Comment by AmbientMalice** [comment]
@Frank-74 I'd be worried about ingame timers with values like that.

**Comment by LegendOfDragoon** [comment]
Better off figuring out how to fix the crackling with FAT + AI=0 in various games (without relying on PBO since it slows down the frame rate in games like Rogue Squadron).

**Comment by Frank-74** [comment]
@LegendOfDragoon Yes, also Goldeneye has a bit of crackle, and stutters with default rdb settings in both DS8 and XA2 versions.  Its not smooth at all.

**Comment by Azimer** [comment]
Yeah...  my audio code needs a revision.  I think it's using streaming dma by default when typically buffered dma is fine.

**Comment by Frank-74** [comment]
I've been checking values in the Project64 debugger for Audio messages, and when checking from `void CAudio::SetViIntr ( DWORD VI_INTR_TIME )`, the VI_INTR_TIME changes between the 'OK' speech with Nintendo logo, and the monkey screams and drums.  This changes the AI from 536 to 535.
```
2015/05/19 10:22:33.739 00836: Audio  : CAudio::SetViIntr: VI_INTR_TIME = 789000 * m_FramesPerSecond = 60
2015/05/19 10:22:33.739 00836: Audio  : CAudio::SetViIntr: CountsPerSecond = 47340000
2015/05/19 10:22:33.739 00836: Audio  : CAudio::SetViIntr: m_BytesPerSecond = 88188
2015/05/19 10:22:33.739 00836: Audio  : CAudio::SetViIntr: m_CountsPerByte = 536
2015/05/19 10:22:33.739 00836: Audio  : CAudio::SetViIntr: AICount = 536.808
2015/05/19 10:22:33.755 00836: Audio  : CAudio::GetLength: Start (m_SecondBuff = 0)
2015/05/19 10:22:33.755 00836: Audio  : CAudio::GetLength: Done (res = 732, TimeLeft = 392587)
2015/05/19 10:22:33.755 00836: Audio  : CAudio::GetStatus: m_Status = 40000000
2015/05/19 10:22:33.755 00836: Audio  : CAudio::LenChanged: Start (g_Reg->AI_LEN_REG = 2944)
2015/05/19 10:22:33.755 00836: Audio  : CAudio::LenChanged: Increasing Second Buffer (m_SecondBuff 0 Increase: 2944)
2015/05/19 10:22:33.755 00836: Audio  : CAudio::LenChanged: Done
2015/05/19 10:22:33.755 00836: Audio  : CAudio::GetLength: Start (m_SecondBuff = 2944)
2015/05/19 10:22:33.755 00836: Audio  : CAudio::GetLength: Done (res = 611, TimeLeft = 327715)
2015/05/19 10:22:33.770 00836: Audio  : CAudio::InterruptTimerDone: Start (m_SecondBuff = 2944)
2015/05/19 10:22:33.770 00836: Audio  : CAudio::InterruptTimerDone: Done
2015/05/19 10:22:33.770 00836: Audio  : CAudio::SetViIntr: VI_INTR_TIME = 787500 * m_FramesPerSecond = 60
2015/05/19 10:22:33.770 00836: Audio  : CAudio::SetViIntr: CountsPerSecond = 47250000
2015/05/19 10:22:33.770 00836: Audio  : CAudio::SetViIntr: m_BytesPerSecond = 88188
2015/05/19 10:22:33.770 00836: Audio  : CAudio::SetViIntr: m_CountsPerByte = 535
2015/05/19 10:22:33.770 00836: Audio  : CAudio::SetViIntr: AICount = 535.787
```
