### ISSUE TITLE
Golden Eye 007

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#5]
EnvMixer in ABI1 has an error causing Golden Eye 007 in-game music to be missing elements (the chimes).

**Comment by cxd4** [comment]
Yeah, I remember noticing this as far back as 0.56 WIP2 from 2008 or so.  When I ran the plugin with _GoldenEye 007_ with 1964's internal RSP redirecting to use HLE audio, it happened right around here, in the logos start-up:
![ngee0002](https://cloud.githubusercontent.com/assets/1396303/7425944/db6541a6-ef88-11e4-9647-f5d5889ce88d.png)

With HLE audio, it sounds like some part of the slick metallic effect was truncated at the beginning of the sound, whereas with LLE audio it sounds just the way we'd remember it in any other case.

Funny that you mention EnvMixer in ABI1 though...I was just looking at the inline asm in that function while replacing it with some consistent C in that last pull request for MinGW compatibility I just filed.  Maybe if I'm lucky playing around with it some more will get something to turn up.

**Comment by Azimer** [comment]
Correct background music (listen to the chimey bells) - https://youtu.be/96q2Wrs4XOA?t=70

I don't have a video of the non-chimey bells but it's missing.  ENVMIXER is to blame.

**Comment by Azimer** [comment]
Seems better but there still seems something off... cdffbe4cf2959fecf85fd9229067c715d42ec0eb

**Comment by Frank-74** [comment]
@Azimer Sounds like the stereo is reversed.  The fade in at the beginning is right to left with LLE, left to right with HLE.

**Comment by LegendOfDragoon** [comment]
@Frank-74 did you ever test RSP interpreter? If not, please test :smile: . If you used RSP recompiler, and the HLE is actually "more accurate", then that should be investigated. I honestly doubt the HLE one is more accurate though.

**Comment by LuismaSP89** [comment]
I don´t know if this helps, but every audio plugin works with chopped audio in Goldeneye 64 for me "Not only in the rare logo, also in the entire game, except "Shunyuan´s  HLE audio 1.8.2 u1" I don´t know if you can take something of that plugin. I only use it for Goldeneye. For the other games i use Azimer´s audio, i think is the best audio plugin for N64 emulators.
By the way, thanks for this plugin and keep it up : )

**Comment by Azimer** [comment]
Not terribly helpful without explaining what you mean by chopped audio and whether you use HLE or LLE. The more detailed or specific an explanation is the better I can understand the issue being conveyed.

**Comment by LuismaSP89** [comment]
Both of them, "HLE & LLE" this happens too with Super mario 64 for example.

With chopped audio i mean that it sounds like a interference or cropped audio in the background music during games.

**Comment by cxd4** [comment]
How are you configuring whether it's HLE or LLE?

What graphics plugin did you test the audio with?

**Comment by LuismaSP89** [comment]
- Setting "In project64" Options>Settings>Plugins> Audio HLE "Enable/Disable Option"

- With Gliden64 last version, and Jabo´s Direct3D 8  1.7.057-ver5

-60 VI/s all the time

**Comment by cxd4** [comment]
Hmm okay so what about Jabo's DirectSound?  You mentioned the XAudio2 code suanyuan used in a plugin but could this maybe be a sound card issue and is it exclusive to just this plugin?  Or do other audio plugins besides suanyuan also have the crackling/popping you mentioned.

**Comment by LuismaSP89** [comment]
RSP 1.7 that comes with last version of project64 "From emucr last update"

With Goldeneye all the audio plugins have the crackling problem, except with suanyuan. I don´t know what it this happening.

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 , do you have fixed audio timing enabled in PJ64? If not, then it's probably related to AI emulation.

**Comment by LuismaSP89** [comment]
Mmm? Do you mean "Sync using audio" option?

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 I mean "Fixed audio timing", it's to the left of "Sync using audio".

**Comment by LuismaSP89** [comment]
Ok, I´m sorry, I got the project 64 in my mother languaje and i didn´t see that option. Yes, it´s unchecked by default.

**Comment by LuismaSP89** [comment]
I think it sounds better with that option checked, but not perfect yet.

**Comment by LuismaSP89** [comment]
Nope, in other games like super mario 64 that options enables crappy sound.

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 ok sounds like the problem is AI emulation. Where did you get Project64 2.2 from? I need to know which binary you're using.

**Comment by LuismaSP89** [comment]
From emucr

This: http://www.emucr.com/2015/07/project64-git-20150715.html

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 Great, that answers my question :smile: . Since you're using a relatively recent version of PJ64 2.2, it's generally best to set AiCountPerByte to 0, when using "Fixed audio timing" . What version of Azimer's Audio are you using? DS8 or XA2? And which WIP #?

**Comment by LuismaSP89** [comment]
It sounds a bit better, thanks a lot for your help ^^
XA2 "Last version from emucr too WIP6"    http://www.emucr.com/2015/07/azimers-hle-audio-plugin-git-20150726.html

**Comment by LegendOfDragoon** [comment]
@LuismaSP89 You're welcome :smiley: . XA2 WIP 6 has some regression with AI emulation, so keep that in mind. Basically that means that it sounds worse with "Fixed audio timing" off, compared to earlier versions (at least in the games I tested) . Although I think earlier versions still have crackling in GoldenEye.

**Comment by Azimer** [comment]
WIP6 is a recent tag to the builds.  Was it an issue in WIP5 too?

I think audio plugins doing the AI emulation should be a thing of the past mostly.

**Comment by LuismaSP89** [comment]
Ok, after testing a lot of configs with plugins:

GlideN64 video plugin: Makes a slow transition between screens "When you see the video start of a mission" and makes little slowdown when change weapons, these two things slows the audio. Jabo´s Direct3D 8 1.7.057-ver5 works very well.

Azimer´s audio WIP 6 works fairly better than WIP 5, but to be perfect, i need to set the "Fixed audio timing" in both.

WIP 6 accelerates the game a little, unless i set "Fixed audio timing". WIth fixed audio timing the game goes between 59-60 VI/s, with fixed audio unchecked stills at 60 VI/s all the time, but i think that acelerates the sound and the game.

LLE audio works better in WIP5 & WIP56, if i set HLE audio, i can experiment worse audio by far.

**Comment by AmbientMalice** [comment]
>WIP 6 accelerates the game a little, unless i set "Fixed audio timing". WIth fixed audio timing the game goes between 59-60 VI/s, with fixed audio unchecked stills at 60 VI/s all the time, but i think that acelerates the sound and the game.

Did you make sure to disable Sync Using Audio? Fixed Audio TIming and Audio Sync are incompatible with each other.

**Comment by Azimer** [comment]
I see the issue with FAT turned off.  I've been doing almost all of my testing with FAT on.  WIP6 is a rework of the audio code in progress.  There's some in progress code that tries to do WIP5 compatible calls but I think I missed something somewhere.  I would like to retain AI Emulation in the plugin as capable.
