### ISSUE TITLE
Pilotwings

### ISSUE THREAD

**Issue by Azimer** [Azimer/AziAudio#6]
Pilotwings64 is missing an emulated filter which causes the title screen music to be bad.  This works well when using BSmiles mupen64plus audio hle.

**Comment by Azimer** [comment]
I am working on this issue now referencing Bobby's code.

**Comment by cxd4** [comment]
I just hope it doesn't have anything to do with ADPCM because now I am SSE-ifying the shit out of that.

**Comment by Azimer** [comment]
Fixed in c172032e859518fb7b702d450f611b7ebb5fa109
