### ISSUE TITLE
Can `vscale' be shifted by a negative amount?

### ISSUE THREAD

**Issue by cxd4** [Azimer/AziAudio#66]
During one of my last PRs I noticed this line 3 times throughout ADPCM:
https://github.com/cxd4/AziAudio/blob/e189652ff03899f954278a6ab79c9ea598dede5a/AziAudio/ABI_Adpcm.cpp#L89

The comment below it reads:
```c
// so this appears to be a fractional scale based
// on the 12 based inverse of the scale value. note
// that this could be negative, in which case we do
// not use the calculated vscale value... see the
// if(code>12) check below
```
This comment leads me to consider two questions.
* Where is this `if (code > 12)` check?  There doesn't seem to be one throughout the file, which means that if `code` was 12, it doesn't seem prevented that we might be shifting right by a negative.
* Why is it **12**, exactly?  The actual shift amount here reads `((12 - code) - 1)`, which simplifies algebraically to `(11 - code)`; therefore the only ways through which the shift amount would not be negative is `if (code > 11)`, not `if (code > 12)`, is false.

**Comment by Azimer** [comment]
I think that comment came from rcp.  I reversed adpcm myself but reused much of his function.  The code works without issue within the subset of commercial game images so I never paid much attention to it.

**Comment by cxd4** [comment]
Hmm.  How about, keep the first sentence of rcp's comment, discard the note about negative shift amounts at the end, and throw in an `assert(code < 12)`?

**Comment by Azimer** [comment]
The check is in there already but perhaps an assert would be better?

https://github.com/cxd4/AziAudio/blob/e189652ff03899f954278a6ab79c9ea598dede5a/AziAudio/ABI_Adpcm.cpp#L19

**Comment by cxd4** [comment]
That explains it!  So the `vscale` calculation is done only once (per iteration of the `while` loop) for performance, but it is only ever read as a source variable within the `InitInput` functions and that like you said is where the (code < 12) / etc. stuff is managed.

I'm thinking about making a readability change to drop the final parameter to that `InitInput` function you linked, and have `vscale` as a local variable that gets defined within the function itself.  That way the calculation of vscale is in the same block of code as whatever checks (if any) to prevent shifting by a negative number, instead of allowing a shift by a negative number and then undoing it mid-way through a later function call.  Sounds like it could be worth it?

**Comment by Azimer** [comment]
I think a better option is to remove code < srange and the respective parameters and put that assert immediately after code is shifted.  assert(code < 12);  There's no reason to recheck this condition except when code is changed.

**Comment by cxd4** [comment]
Actually might have to do it that way yeah, it depends, I was wondering about this?
https://github.com/cxd4/AziAudio/blob/e189652ff03899f954278a6ab79c9ea598dede5a/AziAudio/ABI_Adpcm.cpp#L238

Lines 238 and 241 here have `0xE` passed as the `srange` (second-to-last) parameter, even though just above these lines, `vscale = (0x8000u >> ((srange - code) - 1));`, which means that vscale was calculated based on a right-shift base of `srange`, not `0xE`.  So lines 231 and 234 use srange - code; lines 238 and 241 use 0xE - code...is 0xE - code just a dummy value for srange to prevent the function from complaining that the shift amount was negative?

**Comment by cxd4** [comment]
Alright let's see, so about the reason I made this "issue" was just confusion at what was going on.

You pointed out there really is no issue in practice of the games being emulated, so I made a basic commit just changing part of the comments/added a comment in InitInput to show that the assert could be used to debug but never seems to be needed by games, so minimal changes just to help make a couple things look not as potentially confusing.  Does that seem fine?

**Comment by Azimer** [comment]
0xE is related to the flags & 0x4 (look above in that section of code) where it uses 4 masks 0xC0, 0x30, 0x0C and 0x03 as opposed to 2 masks 0xF0 and 0xF.

Again code and srange are pretty useless in InitInput and the assert check can be done with the proper values using flag & 0x4.

I'd do something like this...  
https://github.com/cxd4/AziAudio/blob/e189652ff03899f954278a6ab79c9ea598dede5a/AziAudio/ABI_Adpcm.cpp#L223
```
assert (((srange - code) - 1) >= 0); // Tests for negative shifts
```
and
```
void InitInput(s32 *inp, int index, u8 icode, u8 mask, u8 shifter, int vscale)
{
	inp[index] = (s16)((icode & mask) << shifter);
	inp[index] = (inp[index] * vscale) >> 16;
}
```
This removes the check from the innerloop.

**Comment by cxd4** [comment]
The only inquiry I have with doing the `assert` outside of the function is that it's less maintainable.  Usually debugging code like calls to assert should be written for stability/thoroughness rather than performance (hence why I #if 0'd it out so that non-debug-testing of the plugin wouldn't call the assert within any loops).

For example if I move my assert outside `InitInput` and into the line you highlighted, that would test the condition within ADPCM2(), yes, but it wouldn't debug negative shift amounts inside of ADPCM1() ( https://github.com/cxd4/AziAudio/blob/e189652ff03899f954278a6ab79c9ea598dede5a/AziAudio/ABI_Adpcm.cpp#L89 ) or ADPCM3() ( https://github.com/cxd4/AziAudio/blob/e189652ff03899f954278a6ab79c9ea598dede5a/AziAudio/ABI_Adpcm.cpp#L352 ), unless there is something unique to just ADPCM2 that causes only a concern for negative right shifts there?

So does that mean we should move the assert outside of InitInput into all 3 of those spots or just the ADPCM2 line you highlighted?

>0xE is related to the flags & 0x4 (look above in that section of code) where it uses 4 masks 0xC0, 0x30, 0x0C and 0x03 as opposed to 2 masks 0xF0 and 0xF.

Yeah, I missed that it was being set to 0xE earlier in the function.

The 0xE in the InitInput call made me think we were overriding the actual value we were shifting right by, when actually srange was set to that earlier based on (Flags & 0x4).  I think in a later pull request I can try to move the Flags & 4 part down closer to the outside of the outer loop to make it easier for people to see that passing 0xE is just a coincidence and that "srange" instead of 0xE could also have been said, since they're equal.

**Comment by Azimer** [comment]
I disagree with it being less maintainable since you are basically checking the value of code.  I do agree however, assert is for debugging and can be removed by the preprocessor.  In this case there's no gain in removing it from where it is for release builds.  We're good.

**Comment by cxd4** [comment]
The disadvantage with my current placement of the assert within the function--the shift amount is still being checked for negativity at a long distance away from the code that actually does the shift.  (code is being shifted within the adpcm routine, while the shift value is being checked in a far away place inside the function InitInput.)  There's nothing "wrong" with this so far as the plugin's performance/compatibility/whatever is concerned, but I like to try to prevent people from having to scroll their eyes up significantly to see far away edge case handling (then they wonder if any even exists at all).

So the way I see it there are a couple approaches at addressing that--
* I could remove the assert I put inside InitInput and do what you said to put them at the 3 adpcm functions next to the definition that does the shift, *AND* also remove the `code` and `srange` parameters to the InitInput function since like you said they're virtually useless (and are unused variables without the assert I did anyway).
* I could leave it as-is where I use the InitInput function as the central function for doing the debugging and leave the code/srange paramters to the function in-tact, closing this issue immediately.

Any preferences there?

**Comment by Azimer** [comment]
I prefer the first option.  code and srange are confusing when they are not actually being used in the function.  I am sure you aren't 100% done with ADPCM so it could be tucked in next time you revisit it.

**Comment by cxd4** [comment]
After the above was merged, this seems to be at a win-win improvement on both ends of the issue, so I think this question has been solved.
