### ISSUE TITLE
Donkey Kong 64 missing monkey scream [HLE] (Regression!)

### ISSUE THREAD

**Issue by oddMLan** [Azimer/AziAudio#74]
Azimer's XA LLE
https://www.dropbox.com/s/5mqa8dh00gbfjys/Azimer%20XA%20LLE.mp3?raw=1

Azimer's XA HLE 
https://www.dropbox.com/s/8kztpw1avkk1waq/Azimer%20XA%20HLE.mp3?raw=1

One of the commits of this build broke it, HLE worked fine in the 2015/05/14 build.
http://www.emucr.com/2015/05/azimers-hle-audio-plugin-git-20150515.html

Changing the RSP makes no difference, tested with the default PJ64 RSP and cxd4's RSP.
Just watch the intro before the rap to be able to hear the problem for yourselves.

**Comment by cxd4** [comment]
Doesn't sound that way for me (XA HLE .mp3), if there really is a regression I need a clearer test.

also what's the pj64 logo doing on emucr o_O

**Comment by cxd4** [comment]
I wonder if I named all my PR branches 420_smoke_weed_every_day, EmuCR would just blindly paste the entire change log without even looking.

**Comment by oddMLan** [comment]
Oh my god... the high pitched monkey screaming at the beginning is missing in the XA HLE .mp3

>also what's the pj64 logo doing on emucr o_O
¯\_(ツ)_/¯

**Comment by cxd4** [comment]
didn't know that was what was meant by "voices" (the actual speech works fine it's just that screaming at the beginning that doesn't), did another pull and I can hear the issue, looking into it.

**Comment by oddMLan** [comment]
That's not the only scream missing actually, the same scream sfx is missing at @0:04 seconds in the HLE version.

**Comment by cxd4** [comment]
That's not important, just the obvious one is good enough for testing.  The VI/s fluctuations in latest pj make it jump over samples and I'm really only concerned with the audible test cases.

**Comment by cxd4** [comment]
Yeah, it's pretty hard to hear right now the way it skips over it, awfully hard to tell whether it's "there" or isn't.  That's the core doing that though I need to find an older version of the emulator so that I can do this testing against whatever suspicions were raised from EmuCR builds.

**Comment by cxd4** [comment]
You can compile it now @oddMLan for the fix to this issue when you're ready.

It turned out to be something one of the accuracy rewrites exposed--wasn't so much of a regression as it revealed itself to be an interesting artifact that one of the cleanups exposing it just recently.

**Comment by oddMLan** [comment]
Great, I will compile it right now.
