### ISSUE TITLE
Star Fox 64 HLE audio issues

### ISSUE THREAD

**Issue by theboy181** [Azimer/AziAudio#79]
HLE audio for Star Fox its very bad. Was working in HLE earlier.

**Comment by Azimer** [comment]
I haven't taken a listen but can you be more descriptive?  I'd hate to not comment right away, go to test and not figure out what you're talking about.

**Comment by Frank-74** [comment]
Speech sounds bad at the very start of the intro.  Short examples.

HLE Star Fox
https://dl.dropboxusercontent.com/u/9498358/n64/HLE_Starfox.mp3

LLE Star Fox
https://dl.dropboxusercontent.com/u/9498358/n64/LLE_Starfox.mp3

**Comment by theboy181** [comment]
So for no description. HLE audio just sounds horible frank has pointed out the issues. 

A weeks ago I used hle audio around the same time as all that rounding wansgokng on with the code and it seemed to be fine then.

**Comment by Azimer** [comment]
Thanks.  This is useful feedback.  I will look into it this evening.

**Comment by Frank-74** [comment]
@Azimer Just built the current master and its no longer an issue.  Seems to be fixed with the last vscale fixes.

**Comment by Azimer** [comment]
Thanks.  I was just going to respond saying such.  I noticed the issue last night with Zelda OOT intro and the horse whinny at the lake.

**Comment by theboy181** [comment]
I apologize, I had moved my PJ folder and the master built to the old location..
